#!/usr/bin/env python3
"""Probe batch15 — fresh PK / MENA / GCC / Europe / Australia / remote hiring inboxes."""
from __future__ import annotations

import csv
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "outreach"))

from smtp_verify import CACHE, _load_csv_map, bounced_emails, mx_hosts, verify_mailbox  # noqa: E402

NEW = [
    # Pakistan / Karachi software
    ("SoftPyramid PK", "softpyramid.com", "Pakistan", "Lahore"),
    ("Sofizar PK", "sofizar.com", "Pakistan", "Lahore"),
    ("Logicose PK", "logicose.com", "Pakistan", "Lahore"),
    ("Appxolute PK", "appxolute.com", "Pakistan", "Islamabad"),
    ("Codehouse PK", "codehouse.pk", "Pakistan", "Islamabad"),
    ("Techverce PK", "techverce.com", "Pakistan", "Lahore"),
    ("Codility Solutions PK", "codilitysolutions.com", "Pakistan", "Lahore"),
    ("ApexSoft PK", "apexsoft.net", "Pakistan", "Lahore"),
    ("FolioSoft PK", "foliosoft.com", "Pakistan", "Lahore"),
    ("CresTech PK", "crestechsoftware.com", "Pakistan", "Lahore"),
    ("Ebryx PK", "ebryx.com", "Pakistan", "Lahore / remote"),
    ("Retailistan PK", "retailistan.com", "Karachi", "Karachi"),
    ("Dastgyr PK", "dastgyr.com", "Karachi", "Karachi"),
    ("Golootlo PK", "golootlo.pk", "Karachi", "Karachi"),
    ("Tez Financial PK", "tezfinancialservices.com", "Pakistan", "Lahore"),
    ("Softinlays PK", "softinlays.com", "Pakistan", "Lahore"),
    ("SoftAct PK", "softact.com", "Pakistan", "Islamabad"),
    ("TechVista PK", "techvistasystems.com", "Pakistan", "Lahore"),
    ("Softsquare PK", "softsquare.biz", "Pakistan", "Lahore"),
    ("Synergy IT PK", "synergy-it.com", "Pakistan", "Lahore"),
    ("CyberVision PK", "cybervisiontech.com", "Pakistan", "Islamabad"),
    ("VTeams PK", "vteams.com", "Pakistan", "Lahore / remote"),
    ("WebHR PK", "webhr.co", "Pakistan", "Lahore / remote"),
    ("Fermat PK", "fermatcommerce.com", "Pakistan", "Lahore / remote"),
    # More PK product / fintech / software
    ("Dukan", "dukan.pk", "Pakistan", "Lahore / remote"),
    ("PriceOye Soft", "priceoye.com", "Pakistan", "Lahore"),
    ("Foodpanda PK Soft", "foodpanda.com.pk", "Karachi", "Karachi"),
    ("Airlift Soft", "airlift.com", "Karachi", "Karachi"),
    ("Swich", "swich.pk", "Karachi", "Karachi"),
    ("Mauqa", "mauqa.com", "Pakistan", "Lahore"),
    ("FindMyProfessionals", "findmyprofessionals.com", "Pakistan", "Lahore"),
    ("KeepTruckin Soft", "gomotive.com", "Karachi", "Karachi / remote"),
    ("Folio3 Soft", "folio3.com", "Karachi", "Karachi"),
    ("Contour Soft", "contoursoftware.com", "Karachi", "Karachi"),
    ("Techlogix Soft", "techlogix.net", "Karachi", "Karachi"),
    ("Inbox Soft", "inbox.com.pk", "Karachi", "Karachi"),
    ("KalSoft Soft", "kalsoft.net", "Karachi", "Karachi"),
    ("Avanza Soft", "avanzasolutions.net", "Karachi", "Karachi"),
    ("NorthBay Soft", "northbay.com", "Karachi", "Karachi"),
    ("SSI Soft", "ssidecisions.net", "Karachi", "Karachi"),
    ("Salsoft Soft", "salsoft.com", "Karachi", "Karachi"),
    ("Gaditek Soft", "gaditek.net", "Karachi", "Karachi"),
    ("Tintash Soft", "tintash.net", "Karachi", "Karachi"),
    ("Xgrid Soft", "xgrid.com", "Karachi", "Karachi"),
    ("Creative Chaos Soft", "creativechaos.com", "Karachi", "Karachi"),
    ("KoderLabs Soft", "koderlabs.net", "Karachi", "Karachi"),
    ("Rolustech Soft", "rolustech.net", "Pakistan", "Lahore"),
    ("Sekel Soft", "sekel.com", "Pakistan", "Lahore"),
    ("DevBatch Soft", "devbatch.net", "Pakistan", "Lahore"),
    ("Techverx Soft", "techverx.net", "Pakistan", "Lahore"),
    ("Speridian Soft", "speridian.net", "Pakistan", "Islamabad"),
    ("Zigron Soft", "zigron.net", "Pakistan", "Islamabad"),
    ("HazenTech Soft", "hazentech.net", "Pakistan", "Islamabad"),
    ("Teknobuilt Soft", "teknobuilt.net", "Pakistan", "Islamabad"),
    ("LMKT Soft", "lmkt.net", "Pakistan", "Islamabad"),
    ("Netsmartz Soft", "netsmartz.net", "Pakistan", "Lahore"),
    ("Code Ninety Soft", "codeninety.net", "Pakistan", "Islamabad"),
    ("Elixir Soft", "elixirtechnologies.com", "Pakistan", "Islamabad"),
    ("DPL Soft", "dpl.pk", "Pakistan", "Islamabad"),
    ("PureLogics Soft", "purelogics.net", "Pakistan", "Lahore"),
    ("Nextbridge Soft", "nextbridge.com", "Pakistan", "Lahore"),
    ("Empiric Soft", "empiric.pk", "Pakistan", "Lahore"),
    ("Recur Soft", "recur.pk", "Pakistan", "Lahore"),
    ("Arpatech Soft", "arpatech.net", "Karachi", "Karachi"),
    ("Softech Soft", "softech.com.pk", "Karachi", "Karachi"),
    ("Mindstorm Soft", "mindstorm.com.pk", "Karachi", "Karachi"),
    ("Vizteck Soft", "vizteck.net", "Karachi", "Karachi"),
    ("Genetech Soft", "genetech.com.pk", "Karachi", "Karachi"),
    ("Powersoft Soft", "powersoft.com.pk", "Pakistan", "Lahore"),
    ("BrightSpyre Soft", "brightspyre.pk", "Pakistan", "Islamabad"),
    ("Shophive Soft", "shophive.pk", "Pakistan", "Lahore"),
    ("Bookme Soft", "bookme.com.pk", "Pakistan", "Lahore"),
    ("Dawaai Soft", "dawaai.com", "Karachi", "Karachi"),
    ("Trax Soft", "trax.com.pk", "Karachi", "Karachi"),
    ("Keenu Soft", "keenu.com.pk", "Karachi", "Karachi"),
    ("Haball Soft", "haball.com.pk", "Karachi", "Karachi"),
    ("Sastaticket Soft", "sastaticket.com", "Karachi", "Karachi"),
    ("PakWheels Soft", "pakwheels.pk", "Karachi", "Karachi"),
    ("Zameen Soft", "zameen.pk", "Karachi", "Karachi"),
    ("OLX Soft", "olx.pk", "Karachi", "Karachi"),
    ("Bykea Soft", "bykea.pk", "Karachi", "Karachi"),
    ("Abhi Soft", "abhi.pk", "Karachi", "Karachi"),
    ("NayaPay Soft", "nayapay.pk", "Karachi", "Karachi"),
    ("Bazaar Soft", "bazaar.pk", "Karachi", "Karachi"),
    ("Retailo Soft", "retailo.pk", "Karachi", "Karachi"),
    ("SadaPay Soft", "sadapay.com", "Karachi", "Karachi"),
    ("Finja Soft", "finja.com", "Pakistan", "Lahore"),
    ("Easypaisa Soft", "easypaisa.pk", "Pakistan", "Islamabad"),
    ("JazzCash Soft", "jazzcash.pk", "Pakistan", "Islamabad"),
    # Kuwait / Qatar / UAE / KSA fresh
    ("UPayments KW", "upayments.com", "Kuwait", "Kuwait / remote"),
    ("SkipCash KW", "skipcash.com", "Kuwait", "Kuwait / remote"),
    ("Xcite KW", "xcite.com", "Kuwait", "Kuwait"),
    ("Warba KW", "warbabank.com", "Kuwait", "Kuwait"),
    ("KIB KW", "kib.com.kw", "Kuwait", "Kuwait"),
    ("Burgan KW", "burgan.com", "Kuwait", "Kuwait"),
    ("Jazeera KW", "jazeeraairways.com", "Kuwait", "Kuwait"),
    ("Kuwait Airways KW", "kuwaitairways.com", "Kuwait", "Kuwait"),
    ("CBK KW", "cbk.com", "Kuwait", "Kuwait"),
    ("Kamco KW", "kamcoinvest.com", "Kuwait", "Kuwait"),
    ("Markaz KW", "markaz.com", "Kuwait", "Kuwait"),
    ("Alghanim KW", "alghanim.com", "Kuwait", "Kuwait"),
    ("Equate KW", "equate.com", "Kuwait", "Kuwait"),
    ("iHorizons QA", "ihorizons.com", "Qatar", "Doha / remote"),
    ("QIB QA", "qib.com.qa", "Qatar", "Doha"),
    ("Dukhan QA", "dukhanbank.com", "Qatar", "Doha"),
    ("Ahli Bank QA", "ahlibank.com.qa", "Qatar", "Doha"),
    ("QIIB QA", "qiib.com.qa", "Qatar", "Doha"),
    ("Hamad QA", "hamad.qa", "Qatar", "Doha"),
    ("Msheireb QA", "msheireb.com", "Qatar", "Doha"),
    ("Estithmar QA", "estithmarholding.com", "Qatar", "Doha"),
    ("GWC QA", "gwclogistics.com", "Qatar", "Doha"),
    ("QTerminals QA", "qterminals.qa", "Qatar", "Doha"),
    ("Mwani QA", "mwani.com.qa", "Qatar", "Doha"),
    ("Qatar Post QA", "qatarpost.qa", "Qatar", "Doha"),
    ("Aspire QA", "aspirezone.qa", "Qatar", "Doha"),
    ("Barwa QA", "barwa.com.qa", "Qatar", "Doha"),
    ("UDC QA", "udcqatar.com", "Qatar", "Doha"),
    ("Qatari Diar QA", "qataridiar.com", "Qatar", "Doha"),
    ("Sarwa AE", "sarwa.co", "UAE", "Dubai / remote"),
    ("Bayzat AE", "bayzat.com", "UAE", "Dubai / remote"),
    ("Huspy AE", "huspy.com", "UAE", "Dubai / remote"),
    ("Qlub AE", "qlub.io", "UAE", "Dubai / remote"),
    ("YAP AE", "yap.com", "UAE", "Dubai / remote"),
    ("Ziina AE", "ziina.com", "UAE", "Dubai / remote"),
    ("Mamo AE", "mamopay.com", "UAE", "Dubai / remote"),
    ("Pyypl AE", "pyypl.com", "UAE", "Dubai / remote"),
    ("Spotii AE", "spotii.com", "UAE", "Dubai / remote"),
    ("Beehive AE", "beehive.ae", "UAE", "Dubai / remote"),
    ("SmartCrowd AE", "smartcrowd.ae", "UAE", "Dubai / remote"),
    ("PayBy AE", "payby.com", "UAE", "Dubai / remote"),
    ("Trukker AE", "trukker.com", "UAE", "Dubai / remote"),
    ("Shipa AE", "shipa.com", "UAE", "Dubai / remote"),
    ("Cartlow AE", "cartlow.com", "UAE", "Dubai / remote"),
    ("Magnitt AE", "magnitt.com", "UAE", "Dubai / remote"),
    ("RemotePass AE", "remotepass.com", "UAE", "Dubai / remote"),
    ("Alaan AE", "alaan.com", "UAE", "Dubai / remote"),
    ("Qashio AE", "qashio.com", "UAE", "Dubai / remote"),
    ("NymCard AE", "nymcard.com", "UAE", "Abu Dhabi / remote"),
    ("Wahed AE", "wahed.com", "UAE", "Dubai / remote"),
    ("BitOasis AE", "bitoasis.net", "UAE", "Dubai / remote"),
    ("Postpay AE", "postpay.io", "UAE", "Dubai / remote"),
    ("Telr AE", "telr.com", "UAE", "Dubai / remote"),
    ("Wio AE", "wio.io", "UAE", "Abu Dhabi / remote"),
    ("G42 AE", "g42.ai", "UAE", "Abu Dhabi / remote"),
    ("Core42 AE", "core42.ai", "UAE", "Abu Dhabi / remote"),
    ("Presight AE", "presight.ai", "UAE", "Abu Dhabi / remote"),
    ("Digital14 AE", "digital14.com", "UAE", "Abu Dhabi"),
    ("Bayanat AE", "bayanat.ai", "UAE", "Abu Dhabi"),
    ("AIQ AE", "aiq.com", "UAE", "Abu Dhabi"),
    ("Soum SA", "soum.sa", "KSA", "Riyadh / remote"),
    ("Nana SA", "nana.sa", "KSA", "Riyadh / remote"),
    ("Sary SA", "sary.com", "KSA", "Riyadh / remote"),
    ("Lucidya SA", "lucidya.com", "KSA", "Riyadh / remote"),
    ("Rasan SA", "rasan.co", "KSA", "Riyadh / remote"),
    ("Tameeni SA", "tameeni.com", "KSA", "Riyadh / remote"),
    ("Nearpay SA", "nearpay.io", "KSA", "Riyadh / remote"),
    ("Moyasar SA", "moyasar.com", "KSA", "Riyadh / remote"),
    ("Mrsool SA", "mrsool.co", "KSA", "Riyadh / remote"),
    ("The Chefz SA", "thechefz.co", "KSA", "Riyadh"),
    ("ToYou SA", "toyou.io", "KSA", "Riyadh"),
    ("Ninja SA", "ninja.sa", "KSA", "Riyadh"),
    ("Syarah SA", "syarah.com", "KSA", "Riyadh / remote"),
    ("Hala SA", "halacards.com", "KSA", "Riyadh / remote"),
    ("Mostaql SA", "mostaql.com", "KSA", "Riyadh / remote"),
    ("Foodics SA", "foodics.com", "KSA", "Riyadh / remote"),
    ("Salla SA", "salla.sa", "KSA", "Riyadh / remote"),
    ("Zid SA", "zid.sa", "KSA", "Riyadh / remote"),
    ("Unifonic SA", "unifonic.com", "KSA", "Riyadh / remote"),
    ("Lean SA", "leantech.me", "KSA", "Riyadh / remote"),
    ("Tabby SA", "tabby.ai", "KSA", "Riyadh / remote"),
    ("Tamara SA", "tamara.co", "KSA", "Riyadh / remote"),
    # Australia fresh
    ("Atlassian AU", "atlassian.com", "Australia", "Sydney / remote"),
    ("Culture Amp AU", "cultureamp.com", "Australia", "Melbourne / remote"),
    ("SafetyCulture AU", "safetyculture.com", "Australia", "Sydney / remote"),
    ("Deputy AU", "deputy.com", "Australia", "Sydney / remote"),
    ("Employment Hero AU", "employmenthero.com", "Australia", "Sydney / remote"),
    ("Linktree AU", "linktr.ee", "Australia", "Melbourne / remote"),
    ("Immutable AU", "immutable.com", "Australia", "Sydney / remote"),
    ("Airwallex AU", "airwallex.com", "Australia", "Melbourne / remote"),
    ("Envato AU", "envato.com", "Australia", "Melbourne / remote"),
    ("Campaign Monitor AU", "campaignmonitor.com", "Australia", "Sydney / remote"),
    ("REA AU", "rea-group.com", "Australia", "Melbourne / remote"),
    ("SEEK AU", "seek.com.au", "Australia", "Melbourne / remote"),
    ("Carsales AU", "carsales.com.au", "Australia", "Melbourne / remote"),
    ("Domain AU", "domain.com.au", "Australia", "Sydney / remote"),
    ("Tyro AU", "tyro.com", "Australia", "Sydney / remote"),
    ("Zip AU", "zip.co", "Australia", "Sydney / remote"),
    ("Afterpay AU", "afterpay.com", "Australia", "Melbourne / remote"),
    ("Brighte AU", "brighte.com.au", "Australia", "Sydney / remote"),
    ("Expert360 AU", "expert360.com", "Australia", "Sydney / remote"),
    ("Airtasker AU", "airtasker.com", "Australia", "Sydney / remote"),
    ("Prospa AU", "prospa.com", "Australia", "Sydney / remote"),
    ("Judo AU", "judo.bank", "Australia", "Melbourne / remote"),
    ("Up AU", "up.com.au", "Australia", "Melbourne / remote"),
    ("Wisetech AU", "wisetechglobal.com", "Australia", "Sydney / remote"),
    ("TechnologyOne AU", "technologyonecorp.com", "Australia", "Brisbane / remote"),
    ("NextDC AU", "nextdc.com", "Australia", "Sydney / remote"),
    ("Finder AU", "finder.com.au", "Australia", "Sydney / remote"),
    ("Xero AU", "xero.com", "Australia", "Melbourne / remote"),
    ("MYOB AU", "myob.com", "Australia", "Melbourne / remote"),
    ("Canva AU", "canva.com", "Australia", "Sydney / remote"),
    # Europe / remote startups not yet mailed
    ("Soldo EU", "soldo.com", "Europe", "London / remote"),
    ("Mambu EU", "mambu.com", "Europe", "Amsterdam / remote"),
    ("Solaris EU", "solarisgroup.com", "Europe", "Berlin / remote"),
    ("Vivid EU", "vivid.money", "Europe", "Berlin / remote"),
    ("Bux EU", "getbux.com", "Europe", "Amsterdam / remote"),
    ("Plum EU", "withplum.com", "Europe", "London / remote"),
    ("Moneybox EU", "moneyboxapp.com", "Europe", "London / remote"),
    ("Octopus EU", "octopus.energy", "Europe", "London / remote"),
    ("Gousto EU", "gousto.co.uk", "Europe", "London / remote"),
    ("Flink EU", "goflink.com", "Europe", "Berlin / remote"),
    ("Getir EU", "getir.com", "Europe", "London / remote"),
    ("Amie EU", "amie.so", "Europe", "Berlin / remote"),
    ("Morgen EU", "morgen.so", "Europe", "Berlin / remote"),
    ("MailerLite EU", "mailerlite.com", "Europe", "Vilnius / remote"),
    ("Brevo EU", "brevo.com", "Europe", "Paris / remote"),
    ("ConfigCat EU", "configcat.com", "Europe", "Budapest / remote"),
    ("ChartMogul EU", "chartmogul.com", "Europe", "Berlin / remote"),
    ("Simple Analytics EU", "simpleanalytics.com", "Europe", "Amsterdam / remote"),
    ("Better Stack EU", "betterstack.com", "Europe", "Prague / remote"),
    ("Checkly EU", "checklyhq.com", "Europe", "Amsterdam / remote"),
    ("Smartlook EU", "smartlook.com", "Europe", "Brno / remote"),
    ("Make EU", "make.com", "Europe", "Prague / remote"),
    ("Windmill EU", "windmill.dev", "Europe", "Paris / remote"),
    ("Heetch EU", "heetch.com", "Europe", "Paris / remote"),
    ("Payload RM", "payloadcms.com", "Remote", "Worldwide remote"),
    ("Kit RM", "kit.com", "Remote", "Worldwide remote"),
    ("Buttondown RM", "buttondown.com", "Remote", "Worldwide remote"),
    ("Statsig RM", "statsig.com", "Remote", "Worldwide remote"),
    ("Svix RM", "svix.com", "Remote", "Worldwide remote"),
    ("Knock RM", "knock.app", "Remote", "Worldwide remote"),
    ("Courier RM", "courier.com", "Remote", "Worldwide remote"),
    ("Polar RM", "polar.sh", "Remote", "Worldwide remote"),
    ("Lemon Squeezy RM", "lemonsqueezy.com", "Remote", "Worldwide remote"),
    ("Gumroad RM", "gumroad.com", "Remote", "Worldwide remote"),
    ("Baremetrics RM", "baremetrics.com", "Remote", "Worldwide remote"),
    ("Fathom RM", "usefathom.com", "Remote", "Worldwide remote"),
    ("LogRocket RM", "logrocket.com", "Remote", "Worldwide remote"),
    ("Upstash RM", "upstash.com", "Remote", "Worldwide remote"),
    ("ClickHouse RM", "clickhouse.com", "Remote", "Worldwide remote"),
    ("Prefect RM", "prefect.io", "Remote", "Worldwide remote"),
    ("Dagster RM", "dagster.io", "Remote", "Worldwide remote"),
    ("Pipedream RM", "pipedream.com", "Remote", "Worldwide remote"),
    ("Fillout RM", "fillout.com", "Remote", "Worldwide remote"),
    ("Jotform RM", "jotform.com", "Remote", "Worldwide remote"),
    ("Typesense RM", "typesense.org", "Remote", "Worldwide remote"),
    ("Xata RM", "xata.io", "Remote", "Worldwide remote"),
    ("Hatchet RM", "hatchet.run", "Remote", "Worldwide remote"),
    ("Calendly RM", "calendly.com", "Remote", "Worldwide remote"),
    ("SavvyCal RM", "savvycal.com", "Remote", "Worldwide remote"),
    ("Motion RM", "usemotion.com", "Remote", "Worldwide remote"),
    ("Reclaim RM", "reclaim.ai", "Remote", "Worldwide remote"),
    ("Clockwise RM", "clockwise.so", "Remote", "Worldwide remote"),
    ("Kraken RM", "kraken.com", "Remote", "Worldwide remote"),
    ("Resend RM", "resend.com", "Remote", "Worldwide remote"),
    ("Loops RM", "loops.so", "Remote", "Worldwide remote"),
    ("Tally EU", "tally.so", "Europe", "Europe / remote"),
    ("Lemlist EU", "lemlist.com", "Europe", "Paris / remote"),
    ("Swan EU", "swan.io", "Europe", "Paris / remote"),
    ("Mirakl EU", "mirakl.com", "Europe", "Paris / remote"),
    ("Voodoo EU", "voodoo.io", "Europe", "Paris / remote"),
    ("Sorare EU", "sorare.com", "Europe", "Paris / remote"),
    ("Pigment EU", "pigment.com", "Europe", "Paris / remote"),
    ("Front EU", "front.com", "Europe", "Paris / remote"),
    ("Aircall EU", "aircall.io", "Europe", "Paris / remote"),
    ("Gorgias EU", "gorgias.com", "Europe", "Paris / remote"),
    ("Shippeo EU", "shippeo.com", "Europe", "Paris / remote"),
    ("Lydia EU", "lydia-app.com", "Europe", "Paris / remote"),
    ("Shine EU", "shine.fr", "Europe", "Paris / remote"),
    ("Doctrine EU", "doctrine.fr", "Europe", "Paris / remote"),
    ("WTTJ EU", "welcometothejungle.com", "Europe", "Paris / remote"),
    ("Alan EU", "alan.com", "Europe", "Paris / remote"),
    ("Qonto EU", "qonto.com", "Europe", "Paris / remote"),
    ("Dataiku EU", "dataiku.com", "Europe", "Paris / remote"),
    ("Photoroom EU", "photoroom.com", "Europe", "Paris / remote"),
    ("Back Market EU", "backmarket.com", "Europe", "Paris / remote"),
    ("Ledger EU", "ledger.com", "Europe", "Paris / remote"),
    ("BlaBlaCar EU", "blablacar.com", "Europe", "Paris / remote"),
    ("Doctolib EU", "doctolib.com", "Europe", "Paris / remote"),
    ("Mistral EU", "mistral.ai", "Europe", "Paris / remote"),
    ("Strapi EU", "strapi.io", "Europe", "Paris / remote"),
    ("Meilisearch EU", "meilisearch.com", "Europe", "Paris / remote"),
    ("Algolia EU", "algolia.com", "Europe", "Paris / remote"),
    ("Pennylane EU", "pennylane.com", "Europe", "Paris / remote"),
    ("PayFit EU", "payfit.com", "Europe", "Paris / remote"),
    ("Prismic EU", "prismic.io", "Europe", "Paris / remote"),
    ("Lago EU", "getlago.com", "Europe", "Paris / remote"),
    ("Scaleway EU", "scaleway.com", "Europe", "Paris / remote"),
    ("OVH EU", "ovhcloud.com", "Europe", "Roubaix / remote"),
    ("Shift Tech EU", "shift-technology.com", "Europe", "Paris / remote"),
    ("Criteo EU", "criteo.com", "Europe", "Paris / remote"),
    ("Contentsquare EU", "contentsquare.com", "Europe", "Paris / remote"),
    ("Deezer EU", "deezer.com", "Europe", "Paris / remote"),
    ("Swile EU", "swile.co", "Europe", "Paris / remote"),
    ("ManoMano EU", "manomano.com", "Europe", "Paris / remote"),
    ("Holded EU", "holded.com", "Europe", "Barcelona / remote"),
    ("CoverManager EU", "covermanager.com", "Europe", "Seville / remote"),
    ("Badi EU", "badi.com", "Europe", "Barcelona / remote"),
    ("Fever EU", "feverup.com", "Europe", "Madrid / remote"),
    ("Idealista EU", "idealista.com", "Europe", "Madrid / remote"),
    ("Sequra EU", "sequra.com", "Europe", "Barcelona / remote"),
    ("Capchase EU", "capchase.com", "Europe", "Madrid / remote"),
    ("Genially EU", "genial.ly", "Europe", "Cordoba / remote"),
    ("Clarity AI EU", "clarity.ai", "Europe", "Madrid / remote"),
    ("Cabify EU", "cabify.com", "Europe", "Madrid / remote"),
    ("Wallapop EU", "wallapop.com", "Europe", "Barcelona / remote"),
    ("Jobandtalent EU", "jobandtalent.com", "Europe", "Madrid / remote"),
    ("Adevinta EU", "adevinta.com", "Europe", "Barcelona / remote"),
    ("Glovo EU", "glovoapp.com", "Europe", "Barcelona / remote"),
    ("Factorial EU", "factorialhr.com", "Europe", "Barcelona / remote"),
    ("Typeform EU", "typeform.com", "Europe", "Barcelona / remote"),
    ("TravelPerk EU", "travelperk.com", "Europe", "Barcelona / remote"),
    ("Satispay EU", "satispay.com", "Europe", "Milan / remote"),
    ("Scalapay EU", "scalapay.com", "Europe", "Milan / remote"),
    ("Bending Spoons EU", "bendingspoons.com", "Europe", "Milan / remote"),
    ("Musixmatch EU", "musixmatch.com", "Europe", "Bologna / remote"),
    ("Moneyfarm EU", "moneyfarm.com", "Europe", "Milan / remote"),
    ("Casavo EU", "casavo.com", "Europe", "Milan / remote"),
    ("Everli EU", "everli.com", "Europe", "Milan / remote"),
    ("Young Platform EU", "youngplatform.com", "Europe", "Turin / remote"),
    ("Conio EU", "conio.com", "Europe", "Milan / remote"),
    ("Fiscozen EU", "fiscozen.it", "Europe", "Milan / remote"),
    ("TeamSystem EU", "teamsystem.com", "Europe", "Pesaro / remote"),
    ("Contents EU", "contents.com", "Europe", "Milan / remote"),
    ("Alokai EU", "alokai.com", "Europe", "Italy / remote"),
    ("Farfetch EU", "farfetch.com", "Europe", "Porto / remote"),
    ("OutSystems EU", "outsystems.com", "Europe", "Lisbon / remote"),
    ("Feedzai EU", "feedzai.com", "Europe", "Lisbon / remote"),
    ("Talkdesk EU", "talkdesk.com", "Europe", "Lisbon / remote"),
    ("Unbabel EU", "unbabel.com", "Europe", "Lisbon / remote"),
    ("Remote.com EU", "remote.com", "Europe", "Lisbon / remote"),
    ("Teamwork EU", "teamwork.com", "Europe", "Cork / remote"),
    ("Fenergo EU", "fenergo.com", "Europe", "Dublin / remote"),
    ("Flipdish EU", "flipdish.com", "Europe", "Dublin / remote"),
    ("Intercom EU", "intercom.com", "Europe", "Dublin / remote"),
    ("Truecaller EU", "truecaller.com", "Europe", "Stockholm / remote"),
    ("Voi EU", "voi.com", "Europe", "Stockholm / remote"),
    ("Kry EU", "kry.se", "Europe", "Stockholm / remote"),
    ("Trustly EU", "trustly.com", "Europe", "Stockholm / remote"),
    ("King EU", "king.com", "Europe", "Stockholm / remote"),
    ("Epidemic Sound EU", "epidemicsound.com", "Europe", "Stockholm / remote"),
    ("Zettle EU", "zettle.com", "Europe", "Stockholm / remote"),
    ("Klarna EU", "klarna.com", "Europe", "Stockholm / remote"),
    ("Spotify EU", "spotify.com", "Europe", "Stockholm / remote"),
    ("Lunar EU", "lunar.app", "Europe", "Copenhagen / remote"),
    ("Pleo EU", "pleo.io", "Europe", "Copenhagen / remote"),
    ("Too Good To Go EU", "toogoodtogo.com", "Europe", "Copenhagen / remote"),
    ("Trustpilot EU", "trustpilot.com", "Europe", "Copenhagen / remote"),
    ("Wolt EU", "wolt.com", "Europe", "Helsinki / remote"),
    ("Aiven EU", "aiven.io", "Europe", "Helsinki / remote"),
    ("Smartly EU", "smartly.io", "Europe", "Helsinki / remote"),
    ("RELEX EU", "relexsolutions.com", "Europe", "Helsinki / remote"),
    ("Supermetrics EU", "supermetrics.com", "Europe", "Helsinki / remote"),
    ("ICEYE EU", "iceye.com", "Europe", "Helsinki / remote"),
    ("Nosto EU", "nosto.com", "Europe", "Helsinki / remote"),
    ("Bolt EU", "bolt.eu", "Europe", "Tallinn / remote"),
    ("Pipedrive EU", "pipedrive.com", "Europe", "Tallinn / remote"),
    ("Veriff EU", "veriff.com", "Europe", "Tallinn / remote"),
    ("Toggl EU", "toggl.com", "Europe", "Tallinn / remote"),
    ("Kahoot EU", "kahoot.com", "Europe", "Oslo / remote"),
    ("Cognite EU", "cognite.com", "Europe", "Oslo / remote"),
    ("Visma EU", "visma.com", "Europe", "Oslo / remote"),
    ("Xeneta EU", "xeneta.com", "Europe", "Oslo / remote"),
    ("Oda EU", "oda.com", "Europe", "Oslo / remote"),
    ("Vivaldi EU", "vivaldi.com", "Europe", "Oslo / remote"),
    ("Proton EU", "proton.me", "Europe", "Geneva / remote"),
    ("Nexthink EU", "nexthink.com", "Europe", "Lausanne / remote"),
    ("Scandit EU", "scandit.com", "Europe", "Zurich / remote"),
    ("Tresorit EU", "tresorit.com", "Europe", "Zurich / remote"),
    ("Exoscale EU", "exoscale.com", "Europe", "Lausanne / remote"),
    ("SonarSource EU", "sonarsource.com", "Europe", "Geneva / remote"),
    ("Bitdefender EU", "bitdefender.com", "Europe", "Bucharest / remote"),
    ("eMAG EU", "emag.ro", "Europe", "Bucharest / remote"),
    ("UiPath EU", "uipath.com", "Europe", "Bucharest / remote"),
    ("Preply EU", "preply.com", "Europe", "Kyiv / remote"),
    ("Ajax EU", "ajax.systems", "Europe", "Kyiv / remote"),
    ("Grammarly EU", "grammarly.com", "Europe", "Kyiv / remote"),
    ("Doist EU", "doist.com", "Europe", "Europe / remote"),
    ("Hotjar EU", "hotjar.com", "Europe", "Malta / remote"),
    ("GitBook EU", "gitbook.com", "Europe", "Europe / remote"),
    ("Cal.com EU", "cal.com", "Europe", "Europe / remote"),
    ("Plausible EU", "plausible.io", "Europe", "Europe / remote"),
    ("Framer EU", "framer.com", "Europe", "Amsterdam / remote"),
    ("Bunny EU", "bunny.net", "Europe", "Slovenia / remote"),
    ("Dynatrace EU", "dynatrace.com", "Europe", "Linz / remote"),
    ("Grafana EU", "grafana.com", "Europe", "Stockholm / remote"),
    ("DeepL EU", "deepl.com", "Europe", "Cologne / remote"),
    ("Aleph Alpha EU", "aleph-alpha.com", "Europe", "Heidelberg / remote"),
    ("Stability AI EU", "stability.ai", "Europe", "London / remote"),
    ("ElevenLabs EU", "elevenlabs.io", "Europe", "London / remote"),
    ("Synthesia EU", "synthesia.io", "Europe", "London / remote"),
    ("Nextcloud EU", "nextcloud.com", "Europe", "Stuttgart / remote"),
    ("Hetzner EU", "hetzner.com", "Europe", "Germany / remote"),
    ("Leapsome EU", "leapsome.com", "Europe", "Berlin / remote"),
    ("HiBob EU", "hibob.com", "Europe", "London / remote"),
    ("Oyster EU", "oysterhr.com", "Europe", "Europe / remote"),
    ("SafetyWing EU", "safetywing.com", "Europe", "Europe / remote"),
    ("PostHog EU", "posthog.com", "Europe", "Europe / remote"),
    ("Langfuse EU", "langfuse.com", "Europe", "Berlin / remote"),
    ("Ghost EU", "ghost.org", "Europe", "Singapore / remote"),
    ("Element EU", "element.io", "Europe", "London / remote"),
    ("Payhawk EU", "payhawk.com", "Europe", "London / remote"),
    ("TransferGo EU", "transfergo.com", "Europe", "Vilnius / remote"),
    ("Trading 212 EU", "trading212.com", "Europe", "London / remote"),
    ("eToro EU", "etoro.com", "Europe", "London / remote"),
    ("Bitstamp EU", "bitstamp.net", "Europe", "Luxembourg / remote"),
    ("Bitpanda EU", "bitpanda.com", "Europe", "Vienna / remote"),
    ("Nexo EU", "nexo.com", "Europe", "Sofia / remote"),
    ("Trezor EU", "trezor.io", "Europe", "Prague / remote"),
    ("Storyblok EU", "storyblok.com", "Europe", "Linz / remote"),
    ("deepset EU", "deepset.ai", "Europe", "Berlin / remote"),
    ("Weaviate EU", "weaviate.io", "Europe", "Amsterdam / remote"),
    ("Qdrant EU", "qdrant.tech", "Europe", "Berlin / remote"),
    ("Dashlane EU", "dashlane.com", "Europe", "Paris / remote"),
    ("Tuta EU", "tuta.com", "Europe", "Hannover / remote"),
    ("pCloud EU", "pcloud.com", "Europe", "Sofia / remote"),
    ("Nord Security EU", "nordsecurity.com", "Europe", "Vilnius / remote"),
    ("Mullvad EU", "mullvad.net", "Europe", "Gothenburg / remote"),
    ("Ecosia EU", "ecosia.org", "Europe", "Berlin / remote"),
    ("Qwant EU", "qwant.com", "Europe", "Paris / remote"),
    ("Restate EU", "restate.dev", "Europe", "Berlin / remote"),
    ("Kestra EU", "kestra.io", "Europe", "Paris / remote"),
    ("Omio EU", "omio.com", "Europe", "Berlin / remote"),
    ("AB Tasty EU", "abtasty.com", "Europe", "Paris / remote"),
    ("Personio EU", "personio.com", "Europe", "Munich / remote"),
    ("Spendesk EU", "spendesk.com", "Europe", "Paris / remote"),
    ("Trade Republic EU", "traderepublic.com", "Europe", "Berlin / remote"),
    ("Scalable Capital EU", "scalable.capital", "Europe", "Munich / remote"),
    ("Moss EU", "getmoss.com", "Europe", "Berlin / remote"),
    ("Freetrade EU", "freetrade.io", "Europe", "London / remote"),
    ("Omnisend EU", "omnisend.com", "Europe", "Vilnius / remote"),
    ("N26 EU", "n26.com", "Europe", "Berlin / remote"),
    ("Contentful EU", "contentful.com", "Europe", "Berlin / remote"),
    ("GetYourGuide EU", "getyourguide.com", "Europe", "Berlin / remote"),
    ("SoundCloud EU", "soundcloud.com", "Europe", "Berlin / remote"),
    ("Zalando EU", "zalando.com", "Europe", "Berlin / remote"),
    ("HelloFresh EU", "hellofresh.com", "Europe", "Berlin / remote"),
    ("AUTO1 EU", "auto1-group.com", "Europe", "Berlin / remote"),
    ("Wefox EU", "wefox.com", "Europe", "Berlin / remote"),
    ("Flix EU", "flix.com", "Europe", "Munich / remote"),
    ("Celonis EU", "celonis.com", "Europe", "Munich / remote"),
    ("Miro EU", "miro.com", "Europe", "Amsterdam / remote"),
    ("Adyen EU", "adyen.com", "Europe", "Amsterdam / remote"),
    ("Mollie EU", "mollie.com", "Europe", "Amsterdam / remote"),
    ("Bird EU", "bird.com", "Europe", "Amsterdam / remote"),
    ("TomTom EU", "tomtom.com", "Europe", "Amsterdam / remote"),
    ("WeTransfer EU", "wetransfer.com", "Europe", "Amsterdam / remote"),
    ("Picnic EU", "picnic.app", "Europe", "Amsterdam / remote"),
    ("Bunq EU", "bunq.com", "Europe", "Amsterdam / remote"),
    ("Backbase EU", "backbase.com", "Europe", "Amsterdam / remote"),
    ("Booking EU", "booking.com", "Europe", "Amsterdam / remote"),
    ("Coolblue EU", "coolblue.nl", "Europe", "Rotterdam / remote"),
    ("Bol EU", "bol.com", "Europe", "Utrecht / remote"),
    ("Monzo EU", "monzo.com", "Europe", "London / remote"),
    ("Revolut EU", "revolut.com", "Europe", "London / remote"),
    ("Wise EU", "wise.com", "Europe", "London / remote"),
    ("Starling EU", "starlingbank.com", "Europe", "London / remote"),
    ("GoCardless EU", "gocardless.com", "Europe", "London / remote"),
    ("OakNorth EU", "oaknorth.com", "Europe", "London / remote"),
    ("Tide EU", "tide.co", "Europe", "London / remote"),
    ("Curve EU", "curve.com", "Europe", "London / remote"),
    ("Paddle EU", "paddle.com", "Europe", "London / remote"),
    ("Thought Machine EU", "thoughtmachine.net", "Europe", "London / remote"),
    ("Featurespace EU", "featurespace.com", "Europe", "Cambridge / remote"),
    ("Tractable EU", "tractable.ai", "Europe", "London / remote"),
    ("Faculty EU", "faculty.ai", "Europe", "London / remote"),
    ("Darktrace EU", "darktrace.com", "Europe", "Cambridge / remote"),
    ("Skyscanner EU", "skyscanner.net", "Europe", "Edinburgh / remote"),
    ("Trainline EU", "thetrainline.com", "Europe", "London / remote"),
    ("Deliveroo EU", "deliveroo.com", "Europe", "London / remote"),
    ("Just Eat EU", "justeattakeaway.com", "Europe", "London / Amsterdam / remote"),
    ("SumUp EU", "sumup.com", "Europe", "London / remote"),
    ("Cleo EU", "meetcleo.com", "Europe", "London / remote"),
    ("Marshmallow EU", "marshmallow.com", "Europe", "London / remote"),
    ("Zepz EU", "zepz.com", "Europe", "London / remote"),
    ("Rapyd EU", "rapyd.net", "Europe", "London / remote"),
    ("Onfido EU", "onfido.com", "Europe", "London / remote"),
    ("Attio EU", "attio.com", "Europe", "London / remote"),
    ("Hopin EU", "hopin.com", "Europe", "London / remote"),
    # More remote product / AI / infra
    ("Neon RM", "neon.tech", "Remote", "Worldwide remote"),
    ("Railway RM", "railway.app", "Remote", "Worldwide remote"),
    ("Render RM", "render.com", "Remote", "Worldwide remote"),
    ("Fly.io RM", "fly.io", "Remote", "Worldwide remote"),
    ("Clerk RM", "clerk.com", "Remote", "Worldwide remote"),
    ("WorkOS RM", "workos.com", "Remote", "Worldwide remote"),
    ("Linear RM", "linear.app", "Remote", "Worldwide remote"),
    ("Raycast RM", "raycast.com", "Remote", "Worldwide remote"),
    ("Retool RM", "retool.com", "Remote", "Worldwide remote"),
    ("Hasura RM", "hasura.io", "Remote", "Worldwide remote"),
    ("PlanetScale RM", "planetscale.com", "Remote", "Worldwide remote"),
    ("Supabase RM", "supabase.com", "Remote", "Worldwide remote"),
    ("Sentry RM", "sentry.io", "Remote", "Worldwide remote"),
    ("PostHog RM", "posthog.com", "Remote", "Worldwide remote"),
    ("Tinybird RM", "tinybird.co", "Remote", "Worldwide remote"),
    ("Inngest RM", "inngest.com", "Remote", "Worldwide remote"),
    ("Trigger.dev RM", "trigger.dev", "Remote", "Worldwide remote"),
    ("Liveblocks RM", "liveblocks.io", "Remote", "Worldwide remote"),
    ("Novu RM", "novu.co", "Remote", "Worldwide remote"),
    ("Dub.co RM", "dub.co", "Remote", "Worldwide remote"),
    ("Twenty RM", "twenty.com", "Remote", "Worldwide remote"),
    ("Plane RM", "plane.so", "Remote", "Worldwide remote"),
    ("AppSmith RM", "appsmith.com", "Remote", "Worldwide remote"),
    ("Tooljet RM", "tooljet.com", "Remote", "Worldwide remote"),
    ("Budibase RM", "budibase.com", "Remote", "Worldwide remote"),
    ("NocoDB RM", "nocodb.com", "Remote", "Worldwide remote"),
    ("Baserow RM", "baserow.io", "Remote", "Worldwide remote"),
    ("Bitwarden RM", "bitwarden.com", "Remote", "Worldwide remote"),
    ("Tailscale RM", "tailscale.com", "Remote", "Worldwide remote"),
    ("Fastly RM", "fastly.com", "Remote", "Worldwide remote"),
    ("Cloudinary RM", "cloudinary.com", "Remote", "Worldwide remote"),
    ("Mux RM", "mux.com", "Remote", "Worldwide remote"),
    ("LiveKit RM", "livekit.io", "Remote", "Worldwide remote"),
    ("Customer.io RM", "customer.io", "Remote", "Worldwide remote"),
    ("Braze RM", "braze.com", "Remote", "Worldwide remote"),
    ("OneSignal RM", "onesignal.com", "Remote", "Worldwide remote"),
    ("CleverTap RM", "clevertap.com", "Remote", "Worldwide remote"),
    ("MoEngage RM", "moengage.com", "Remote", "Worldwide remote"),
    ("Chatwoot RM", "chatwoot.com", "Remote", "Worldwide remote"),
    ("Crisp RM", "crisp.chat", "Remote", "Worldwide remote"),
    ("incident.io RM", "incident.io", "Remote", "Worldwide remote"),
    ("Rootly RM", "rootly.com", "Remote", "Worldwide remote"),
    ("Honeycomb RM", "honeycomb.io", "Remote", "Worldwide remote"),
    ("Sourcegraph RM", "sourcegraph.com", "Remote", "Worldwide remote"),
    ("Codecov RM", "codecov.io", "Remote", "Worldwide remote"),
    ("AssemblyAI RM", "assemblyai.com", "Remote", "Worldwide remote"),
    ("RunPod RM", "runpod.io", "Remote", "Worldwide remote"),
    ("Together AI RM", "together.ai", "Remote", "Worldwide remote"),
    ("Fireworks AI RM", "fireworks.ai", "Remote", "Worldwide remote"),
    ("Anyscale RM", "anyscale.com", "Remote", "Worldwide remote"),
    ("Weights Biases RM", "wandb.ai", "Remote", "Worldwide remote"),
    ("Labelbox RM", "labelbox.com", "Remote", "Worldwide remote"),
    ("Lovable RM", "lovable.dev", "Remote", "Worldwide remote"),
    ("Replicate RM", "replicate.com", "Remote", "Worldwide remote"),
    ("Modal RM", "modal.com", "Remote", "Worldwide remote"),
    ("Airbyte RM", "airbyte.com", "Remote", "Worldwide remote"),
    ("dbt Labs RM", "getdbt.com", "Remote", "Worldwide remote"),
    ("Fivetran RM", "fivetran.com", "Remote", "Worldwide remote"),
    ("Metabase RM", "metabase.com", "Remote", "Worldwide remote"),
    ("Hex RM", "hex.tech", "Remote", "Worldwide remote"),
    ("BrowserStack RM", "browserstack.com", "Remote", "Worldwide remote"),
    ("Freshworks RM", "freshworks.com", "Remote", "Worldwide remote"),
    ("Chargebee RM", "chargebee.com", "Remote", "Worldwide remote"),
    ("Razorpay RM", "razorpay.com", "Remote", "Worldwide remote"),
    ("Postman RM", "postman.com", "Remote", "Worldwide remote"),
    ("Apollo RM", "apollo.io", "Remote", "Worldwide remote"),
    ("Clay RM", "clay.com", "Remote", "Worldwide remote"),
    ("Ashby RM", "ashbyhq.com", "Remote", "Worldwide remote"),
    ("Deel RM", "deel.com", "Remote", "Worldwide remote"),
    ("Rippling RM", "rippling.com", "Remote", "Worldwide remote"),
    ("Webflow RM", "webflow.com", "Remote", "Worldwide remote"),
    ("ClickUp RM", "clickup.com", "Remote", "Worldwide remote"),
    ("Zapier RM", "zapier.com", "Remote", "Worldwide remote"),
    ("Buffer RM", "buffer.com", "Remote", "Worldwide remote"),
    ("Help Scout RM", "helpscout.com", "Remote", "Worldwide remote"),
    ("Close RM", "close.com", "Remote", "Worldwide remote"),
    ("Beehiiv RM", "beehiiv.com", "Remote", "Worldwide remote"),
    ("Substack RM", "substack.com", "Remote", "Worldwide remote"),
    ("Directus RM", "directus.io", "Remote", "Worldwide remote"),
    ("Appwrite RM", "appwrite.io", "Remote", "Worldwide remote"),
    ("Formbricks RM", "formbricks.com", "Remote", "Worldwide remote"),
    ("OpenStatus RM", "openstatus.dev", "Remote", "Worldwide remote"),
    ("Tiptap RM", "tiptap.dev", "Remote", "Worldwide remote"),
    ("Outline RM", "getoutline.com", "Remote", "Worldwide remote"),
    ("Standard Notes RM", "standardnotes.com", "Remote", "Worldwide remote"),
    ("Plain RM", "plain.com", "Remote", "Worldwide remote"),
    ("FireHydrant RM", "firehydrant.com", "Remote", "Worldwide remote"),
    ("Chronosphere RM", "chronosphere.io", "Remote", "Worldwide remote"),
    ("Gitea RM", "gitea.com", "Remote", "Worldwide remote"),
    ("UpCloud EU", "upcloud.com", "Europe", "Helsinki / remote"),
    ("Vultr RM", "vultr.com", "Remote", "Worldwide remote"),
    ("DigitalOcean RM", "digitalocean.com", "Remote", "Worldwide remote"),
    ("Imgix RM", "imgix.com", "Remote", "Worldwide remote"),
    ("Agora RM", "agora.io", "Remote", "Worldwide remote"),
    ("Mailgun RM", "mailgun.com", "Remote", "Worldwide remote"),
    ("Postmark RM", "postmarkapp.com", "Remote", "Worldwide remote"),
    ("Bubble RM", "bubble.io", "Remote", "Worldwide remote"),
    ("Softr RM", "softr.io", "Remote", "Worldwide remote"),
    ("Glide RM", "glideapps.com", "Remote", "Worldwide remote"),
    ("Height RM", "height.app", "Remote", "Worldwide remote"),
    ("Shortcut RM", "shortcut.com", "Remote", "Worldwide remote"),
    ("Whimsical RM", "whimsical.com", "Remote", "Worldwide remote"),
    ("Excalidraw RM", "excalidraw.com", "Remote", "Worldwide remote"),
    ("tldraw RM", "tldraw.com", "Remote", "Worldwide remote"),
    ("Census RM", "getcensus.com", "Remote", "Worldwide remote"),
    ("Hightouch RM", "hightouch.com", "Remote", "Worldwide remote"),
    ("RudderStack RM", "rudderstack.com", "Remote", "Worldwide remote"),
    ("Snowplow EU", "snowplow.io", "Europe", "London / remote"),
    ("Preset RM", "preset.io", "Remote", "Worldwide remote"),
    ("Mode RM", "mode.com", "Remote", "Worldwide remote"),
    ("Observable RM", "observablehq.com", "Remote", "Worldwide remote"),
    ("Speechmatics EU", "speechmatics.com", "Europe", "Cambridge / remote"),
    ("Comet ML RM", "comet.com", "Remote", "Worldwide remote"),
    ("Snorkel AI RM", "snorkel.ai", "Remote", "Worldwide remote"),
    ("Orb RM", "withorb.com", "Remote", "Worldwide remote"),
    ("Metronome RM", "metronome.com", "Remote", "Worldwide remote"),
    ("Marqeta RM", "marqeta.com", "Remote", "Worldwide remote"),
    ("Unit Finance RM", "unit.co", "Remote", "Worldwide remote"),
    ("Column RM", "column.com", "Remote", "Worldwide remote"),
    ("Modern Treasury RM", "moderntreasury.com", "Remote", "Worldwide remote"),
    ("Increase RM", "increase.com", "Remote", "Worldwide remote"),
    ("Nubank RM", "nubank.com.br", "Remote", "Sao Paulo / remote"),
    ("Xendit RM", "xendit.co", "Remote", "Jakarta / Singapore / remote"),
    ("Midtrans RM", "midtrans.com", "Remote", "Jakarta / remote"),
    ("Traveloka RM", "traveloka.com", "Remote", "Jakarta / remote"),
    ("GoTo RM", "gotocompany.com", "Remote", "Jakarta / remote"),
    ("Tokopedia RM", "tokopedia.com", "Remote", "Jakarta / remote"),
    ("Bukalapak RM", "bukalapak.com", "Remote", "Jakarta / remote"),
    ("Ajaib RM", "ajaib.co.id", "Remote", "Jakarta / remote"),
    ("Stockbit RM", "stockbit.com", "Remote", "Jakarta / remote"),
    ("Lazada SG", "lazada.com", "Singapore", "Singapore / remote"),
    ("Zalora SG", "zalora.com", "Singapore", "Singapore / remote"),
    ("PropertyGuru SG", "propertyguru.com", "Singapore", "Singapore / remote"),
    ("Circles SG", "circles.life", "Singapore", "Singapore / remote"),
    ("Advance.AI SG", "advance.ai", "Singapore", "Singapore / remote"),
    ("StraitsX SG", "straitsx.com", "Singapore", "Singapore / remote"),
    ("Validus SG", "validus.sg", "Singapore", "Singapore / remote"),
    ("FinAccel SG", "finaccel.com", "Singapore", "Singapore / remote"),
    ("BigPay MY", "bigpayme.com", "Malaysia", "Kuala Lumpur / remote"),
    ("Lalamove RM", "lalamove.com", "Remote", "Hong Kong / remote"),
    ("Klook RM", "klook.com", "Remote", "Hong Kong / remote"),
    ("PhonePe RM", "phonepe.com", "Remote", "India / remote"),
    ("CRED RM", "cred.club", "Remote", "India / remote"),
    ("Groww RM", "groww.in", "Remote", "India / remote"),
    ("Zerodha RM", "zerodha.com", "Remote", "India / remote"),
    ("Meesho RM", "meesho.com", "Remote", "India / remote"),
    ("Swiggy RM", "swiggy.com", "Remote", "India / remote"),
    ("Zomato RM", "zomato.com", "Remote", "India / remote"),
    ("ShareChat RM", "sharechat.com", "Remote", "India / remote"),
    ("Dream11 RM", "dream11.com", "Remote", "India / remote"),
    ("Druva RM", "druva.com", "Remote", "India / remote"),
    ("Icertis RM", "icertis.com", "Remote", "India / remote"),
    ("Persistent RM", "persistent.com", "Remote", "India / remote"),
    ("Atome SG", "atome.sg", "Singapore", "Singapore / remote"),
    ("Garena SG", "garena.com", "Singapore", "Singapore / remote"),
    ("Jumia EG", "jumia.com", "Egypt", "Cairo / remote"),
    ("Instabug EG", "instabug.com", "Egypt", "Cairo / remote"),
    ("Paymob EG", "paymob.com", "Egypt", "Cairo / remote"),
    ("Breadfast EG", "breadfast.com", "Egypt", "Cairo / remote"),
    ("Trella EG", "trella.app", "Egypt", "Cairo / remote"),
    ("Telda EG", "telda.app", "Egypt", "Cairo / remote"),
    ("Money Fellows EG", "moneyfellows.com", "Egypt", "Cairo / remote"),
    ("Khazna EG", "khazna.app", "Egypt", "Cairo / remote"),
    ("Valify EG", "valify.me", "Egypt", "Cairo / remote"),
    ("Bosta EG", "bosta.co", "Egypt", "Cairo / remote"),
    ("Synapse EG", "synapse-analytics.io", "Egypt", "Cairo / remote"),
    ("Incorta EG", "incorta.com", "Egypt", "Cairo / remote"),
    ("Flat6Labs EG", "flat6labs.com", "Egypt", "Cairo / remote"),
    ("DSquares EG", "dsquares.com", "Egypt", "Cairo / remote"),
    ("Cequens EG", "cequens.com", "Egypt", "Cairo / remote"),
    ("ITWorx EG", "itworx.com", "Egypt", "Cairo / remote"),
    ("Link Development EG", "linkdev.com", "Egypt", "Cairo / remote"),
    ("MaxAB EG", "maxab.io", "Egypt", "Cairo / remote"),
    ("Vezeeta EG", "vezeeta.com", "Egypt", "Cairo / remote"),
    ("Swvl EG", "swvl.com", "Egypt", "Cairo / Dubai / remote"),
    ("OpenSooq JO", "opensooq.com", "Jordan", "Amman / remote"),
    ("Abwaab JO", "abwaab.com", "Jordan", "Amman / remote"),
    ("Mawdoo3 JO", "mawdoo3.com", "Jordan", "Amman / remote"),
    ("ProgressSoft JO", "progressoft.com", "Jordan", "Amman / remote"),
    ("ZenHR JO", "zenhr.com", "Jordan", "Amman / remote"),
    ("MadfooatCom JO", "madfooat.com", "Jordan", "Amman / remote"),
    ("Tarabut BH", "tarabut.com", "Bahrain", "Manama / remote"),
    ("Benefit BH", "benefit.bh", "Bahrain", "Manama / remote"),
    ("Rain BH", "rain.bh", "Bahrain", "Manama / remote"),
    ("C5 BH", "c5accelerate.com", "Bahrain", "Manama"),
    ("Tenmou BH", "tenmou.me", "Bahrain", "Manama"),
]

TRY = ("careers", "hr", "recruiting", "jobs", "people", "hiring", "recruitment", "talent")
GOOGLEISH = ("google", "gmail", "aspmx", "googlemail", "larksuite", "smtp.goog")
TARGET = {
    "Karachi",
    "Pakistan",
    "MENA",
    "UAE",
    "KSA",
    "Qatar",
    "Bahrain",
    "Kuwait",
    "Oman",
    "Egypt",
    "Jordan",
    "Lebanon",
    "Singapore",
    "Malaysia",
    "Europe",
    "Australia",
}
DONE = {
    "invalid",
    "reject",
    "bounce",
    "no-mx",
    "catch-all",
    "accept-then-unknown",
    "probe-blocked",
    "strict-valid",
}
DEAD = {"catch-all", "no-mx", "probe-blocked"}


def main() -> int:
    sent_e: set[str] = set()
    sent_c: set[str] = set()
    sent_d: set[str] = set()
    with (ROOT / "outreach" / "sent_log.csv").open(encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            if row.get("status") != "sent":
                continue
            email = (row.get("email") or "").lower()
            company = (row.get("company") or "").strip().lower()
            sent_e.add(email)
            if company and company != "test":
                sent_c.add(company)
            if "@" in email:
                sent_d.add(email.split("@", 1)[1])

    cache = _load_csv_map(CACHE)
    bounces = bounced_emails()
    dead_domains = {e.split("@", 1)[1] for e, st in cache.items() if "@" in e and st in DEAD}
    probed_locals: dict[str, set[str]] = defaultdict(set)
    for email in cache:
        if "@" in email:
            local, domain = email.split("@", 1)
            probed_locals[domain].add(local)

    seen: set[str] = set()
    fresh: list[tuple[str, str, str, str, list[str]]] = []
    for name, domain, region, city in NEW:
        domain = domain.lower().strip()
        if not domain or domain in sent_d or domain in dead_domains:
            continue
        if domain in seen:
            continue
        base = (
            name.lower()
            .replace(" careers", "")
            .replace(" digital", "")
            .replace(" soft", "")
            .replace(" tech", "")
            .replace(" au", "")
            .replace(" eu", "")
            .replace(" rm", "")
            .replace(" pk", "")
            .replace(" kw", "")
            .replace(" qa", "")
            .replace(" ae", "")
            .replace(" sa", "")
            .replace(" eg", "")
            .replace(" jo", "")
            .replace(" bh", "")
            .replace(" sg", "")
            .replace(" my", "")
            .strip()
        )
        if name.strip().lower() in sent_c or any(base == c or (len(base) > 4 and (base in c or c in base)) for c in sent_c):
            continue
        seen.add(domain)
        missing = []
        for loc in TRY:
            email = f"{loc}@{domain}"
            if loc in probed_locals[domain] or email in sent_e or email in bounces or cache.get(email) in DONE:
                continue
            missing.append(loc)
        if missing:
            fresh.append((name, domain, region, city, missing[:4]))

    print(f"fresh companies after filters: {len(fresh)}", flush=True)

    google = []
    other = 0
    for name, domain, region, city, locs in fresh:
        try:
            hosts = mx_hosts(domain)
        except Exception:
            hosts = []
        mxblob = " ".join(hosts).lower()
        if any(token in mxblob for token in GOOGLEISH):
            pri = (
                -2
                if region in {"Karachi", "Pakistan"}
                else -1
                if region in {"Kuwait", "Qatar", "Australia", "UAE", "KSA", "Egypt", "MENA", "Jordan", "Bahrain"}
                else (0 if region in TARGET else 1)
            )
            google.append((pri, region, name, domain, city, locs))
        else:
            other += 1
    google.sort(key=lambda item: (item[0], item[1], item[2].lower()))
    print(f"google/lark: {len(google)}  other mx skipped: {other}", flush=True)
    print("regions", Counter(item[1] for item in google), flush=True)
    for item in google[:30]:
        print(f"  plan {item[3]:32} try={item[5]}  {item[2]} [{item[1]}]", flush=True)

    found: list[dict[str, str]] = []
    stats: Counter[str] = Counter()
    target_hits = 14
    for i, (_pri, region, name, domain, city, locs) in enumerate(google, 1):
        if len(found) >= target_hits:
            print(f"hit {target_hits}, stop", flush=True)
            break
        for loc in locs:
            email = f"{loc}@{domain}"
            print(f"[{i}/{len(google)}] probe {email} ({name} / {region})", flush=True)
            ok, detail = verify_mailbox(email)
            time.sleep(0.2)
            if ok:
                stats["ok"] += 1
                print(f"  OK  {email}  {detail[:110]}", flush=True)
                found.append(
                    {
                        "Company": name.rsplit(" ", 1)[0] if name.rsplit(" ", 1)[-1] in {
                            "PK", "KW", "QA", "AE", "SA", "EG", "JO", "BH", "SG", "MY", "AU", "EU", "RM"
                        } else name,
                        "Region": region,
                        "City": city,
                        "HR / Recruiter Email": email,
                        "Email Source": "guessed pattern (verify before sending)",
                        "Other Emails": "",
                        "Domain": domain,
                        "Careers / Apply URL": f"https://{domain}/careers",
                        "Sample Role": "",
                        "SMTP Verification": detail[:400],
                    }
                )
                break
            tag = "catch-all" if "catch-all" in detail.lower() else "fail"
            stats[tag] += 1
            print(f"  NO  {email}  {detail[:130]}", flush=True)
            if "catch-all" in detail.lower():
                break

    out = ROOT / "output" / "emails_shortlist_batch15_2026-08-14.csv"
    fields = [
        "Company",
        "Region",
        "City",
        "HR / Recruiter Email",
        "Email Source",
        "Other Emails",
        "Domain",
        "Careers / Apply URL",
        "Sample Role",
        "SMTP Verification",
    ]
    with out.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(found)
    print("\nSTATS", dict(stats), flush=True)
    print("WROTE", out, "rows", len(found), flush=True)
    for row in found:
        print(f"  {row['HR / Recruiter Email']:40} {row['Company']} [{row['Region']}]", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
