from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
# Re-export for letter paths / apply pipeline.
load_dotenv(ROOT / ".env")

OUTPUT_DIR = ROOT / "output"
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

HUNTER_API_KEY = os.getenv("HUNTER_API_KEY", "").strip()

# Title must look like an engineering role, then skills decide relevance.
RELEVANT_TITLE_HINTS = (
    "engineer",
    "developer",
    "programmer",
    "software",
    "frontend",
    "front-end",
    "front end",
    "backend",
    "back-end",
    "back end",
    "full stack",
    "fullstack",
    "full-stack",
    "react",
    "next.js",
    "nextjs",
    "python",
    "ai ",
    " ai",
    "llm",
    "machine learning",
    "ml engineer",
    "ml ops",
    "mlops",
    "data scientist",
    "applied scientist",
    "research engineer",
    "web developer",
    "web engineer",
    "product engineer",
    "software engineer",
    "software developer",
    "frontend engineer",
    "front-end engineer",
    "front end engineer",
    "frontend developer",
    "ai engineer",
    "artificial intelligence",
)

EXCLUDE_TITLE_HINTS = (
    "sales",
    "account executive",
    "recruiter",
    "talent acquisition",
    "customer success",
    "support specialist",
    "helpdesk",
    "help desk",
    "nurse",
    "pharmacist",
    "accountant",
    "bookkeeper",
    "beekeeper",
    "driver",
    "warehouse",
    "cashier",
    "marketing manager",
    "seo specialist",
    "content writer",
    "copywriter",
    "legal counsel",
    "attorney",
    "teacher",
    "principal",
    "product owner",
    "scrum master",
    "project manager",
    "ios developer",
    "android developer",
    "php developer",
    "wordpress",
    "shopify developer",
    "unity",
    "unreal",
    "golang only",
    "java developer",
    "dotnet",
    ".net developer",
    "c# developer",
    "sap ",
    "oracle ebs",
    "mainframe",
)

SKILL_PATTERNS: dict[str, tuple[str, ...]] = {
    "Next.js": (r"\bnext\.?\s*js\b", r"\bnextjs\b"),
    "React": (r"\breact(?:\.js)?\b",),
    "TypeScript": (r"\btypescript\b",),
    "JavaScript": (r"\bjavascript\b", r"\bes6\b"),
    "Python": (r"\bpython\b",),
    "FastAPI": (r"\bfastapi\b",),
    "Django": (r"\bdjango\b",),
    "Flask": (r"\bflask\b",),
    "Node.js": (r"\bnode\.?\s*js\b",),
    "AI Engineering": (
        r"\bai engineer(?:ing)?\b",
        r"\bgenerative ai\b",
        r"\bgenai\b",
        r"\bllm(?:s)?\b",
        r"\blarge language models?\b",
        r"\bprompt engineer(?:ing)?\b",
    ),
    "LangChain": (r"\blangchain\b", r"\blanggraph\b"),
    "RAG": (r"\brag\b", r"retrieval[-\s]?augmented"),
    "OpenAI / GPT": (r"\bopenai\b", r"\bgpt-?\d", r"\bchatgpt\b"),
    "Machine Learning": (r"\bmachine learning\b", r"\bml engineer\b", r"\bdeep learning\b"),
    "Full Stack": (r"\bfull[\s-]?stack\b",),
    "Backend": (r"\bback[\s-]?end\b",),
    "Frontend": (r"\bfront[\s-]?end\b",),
}

CORE_SKILLS = {
    "Next.js",
    "React",
    "Python",
    "FastAPI",
    "Django",
    "Flask",
    "AI Engineering",
    "LangChain",
    "RAG",
    "OpenAI / GPT",
    "Machine Learning",
}

TITLE_WEIGHT = 12
DESCRIPTION_WEIGHT = 3
MIN_SCORE = 8
MIN_SCORE_PK = 6

PAKISTAN_TZ_OFFSETS = {4.5, 5, 5.5, 6}

GREENHOUSE_BOARDS = (
    "turing",
    "thoughtworks",
    "careem",
    "motive",
    "talabat",
    "deliveryhero",
    "monzo",
    "wise",
    "personio",
    "n26",
    "miro",
    "doctolib",
    "deliveroo",
    "contentful",
    "intercom",
    "typeform",
    "getyourguide",
    "hellofresh",
    "gocardless",
    "paddle",
    "skyscanner",
    "klarna",
    "celonis",
    "aiven",
    "pipedrive",
    "factorial",
    "travelperk",
    "photoroom",
    "mistralai",
    "pleo",
    "trustpilot",
    "wolt",
    "remote",
    "canva",
    "atlassian",
    "cultureamp",
    "airwallex",
    "employmenthero",
    "safetyculture",
    "buildkite",
    "rokt",
    "siteminder",
    "xero",
    "envato",
    "seek",
    "afterpay",
    "immutable",
    "linktree",
    "deputy",
    "noon",
    "tabby",
    "tamara",
    "checkout",
    "revolut",
    "spotify",
    "bolt",
    "adyen",
    "mollie",
    "algolia",
    "deepl",
    "elevenlabs",
    "synthesia",
    "posthog",
    "supabase",
    "sentry",
    "vercel",
    "stripe",
)

LEVER_BOARDS = (
    "toptal",
    "spotify",
    "netflix",
    "reddit",
    "canva",
    "atlassian",
)

JOBICY_TAGS = (
    "react",
    "python",
    "typescript",
    "machine-learning",
    "engineering",
    "software-engineering",
    "frontend",
)

HIMALAYAS_QUERIES = (
    "react nextjs",
    "python backend fastapi django",
    "AI engineer LLM",
    "machine learning engineer",
    "full stack typescript",
)

REMOTIVE_SEARCHES = (
    "AI engineer",
    "product engineer",
    "software engineer",
    "frontend engineer",
    "python",
    "react",
    "machine learning",
    "Pakistan",
    "Karachi",
    "Lahore",
    "Islamabad",
    "Dubai",
    "UAE",
    "Saudi",
    "Kuwait",
    "Qatar",
    "Doha",
    "Egypt",
    "London",
    "Berlin",
    "Amsterdam",
    "Europe",
    "EMEA",
    "Australia",
    "Sydney",
    "Melbourne",
    "MENA",
    "Middle East",
    "remote worldwide",
)

JAZZHR_BOARDS = (
    ("10pearls", "10Pearls", "10pearls.com"),
    ("venturedive", "VentureDive", "venturedive.com"),
    ("arbisoft", "Arbisoft", "arbisoft.com"),
    ("folio3", "Folio3", "folio3.com"),
    ("confiz", "Confiz", "confiz.com"),
    ("devsinc", "Devsinc", "devsinc.com"),
    ("emumba", "Emumba", "emumba.com"),
    ("tkxel", "Tkxel", "tkxel.com"),
)

PK_KNOWN_EMAILS = {
    "10pearls.com": ["careers@10pearls.com", "info@10pearls.com"],
    "arbisoft.com": ["contact@arbisoft.com"],
    "cubix.co": ["hr@cubixlabs.com", "info@cubix.co"],
    "cubixlabs.com": ["hr@cubixlabs.com"],
    "devsinc.com": ["sales@devsinc.com", "global.business@devsinc.com"],
    "careem.com": ["careers@careem.com"],
    "venturedive.com": ["careers@venturedive.com", "hr@venturedive.com"],
    "sadapay.pk": ["careers@sadapay.pk", "hello@sadapay.pk"],
}

PK_COMPANY_DOMAINS = {
    "10pearls": "10pearls.com",
    "10 pearls": "10pearls.com",
    "arbisoft": "arbisoft.com",
    "folio3": "folio3.com",
    "folio 3": "folio3.com",
    "venturedive": "venturedive.com",
    "venture dive": "venturedive.com",
    "confiz": "confiz.com",
    "devsinc": "devsinc.com",
    "emumba": "emumba.com",
    "tkxel": "tkxel.com",
    "cubix": "cubix.co",
    "systems limited": "systemsltd.com",
    "systems ltd": "systemsltd.com",
    "careem": "careem.com",
    "thoughtworks": "thoughtworks.com",
    "turing": "turing.com",
    "sadapay": "sadapay.pk",
    "sada pay": "sadapay.pk",
    "afiniti": "afiniti.com",
    "ibex": "ibex.co",
    "tintash": "tintash.com",
    "gaditek": "gaditek.com",
    "xgrid": "xgrid.co",
    "netsol": "netsoltech.com",
    "securiti": "securiti.ai",
    "motive": "gomotive.com",
}

PK_CONTACT_PATHS = (
    "/impressum",
    "/imprint",
    "/legal-notice",
    "/contact",
    "/contact-us",
    "/contactus",
    "/get-in-touch",
    "/careers",
    "/jobs",
    "/join",
    "/join-us",
    "/work-with-us",
    "/hiring",
    "/about",
    "/about-us",
    "/en/contact",
    "/en/careers",
    "/en/impressum",
    "/",
)

ATS_DOMAINS = {
    "greenhouse.io",
    "boards.greenhouse.io",
    "lever.co",
    "jobs.lever.co",
    "myworkdayjobs.com",
    "icims.com",
    "smartrecruiters.com",
    "jobvite.com",
    "ashbyhq.com",
    "jobs.ashbyhq.com",
    "workable.com",
    "apply.workable.com",
    "breezy.hr",
    "recruitee.com",
    "teamtailor.com",
    "comeet.co",
    "remoteok.com",
    "remoteok.io",
    "remotive.com",
    "himalayas.app",
    "jobicy.com",
    "arbeitnow.com",
    "weworkremotely.com",
    "linkedin.com",
    "indeed.com",
    "glassdoor.com",
    "wellfound.com",
    "angel.co",
    "applytojob.com",
    "jazzhr.com",
    "jobz.pk",
}

GENERIC_HR_LOCAL_PARTS = (
    "hr",
    "careers",
    "jobs",
    "recruiting",
    "recruitment",
    "talent",
    "people",
    "hiring",
    "join",
    "apply",
    "team",
)
