from __future__ import annotations

import csv
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path

from job_hunter.emails import _scrape_contact_emails, guess_generic_emails, pick_hr_email
from job_hunter.http import HttpClient
from job_hunter.textutil import extract_emails, html_to_text

JUNK_LOCAL = (
    "accommodation",
    "accomodation",
    "accessibleinterview",
    "paytransparency",
    "noreply",
    "no-reply",
    "donotreply",
    "privacy",
    "legal",
    "support",
    "press",
    "media",
    "sales",
    "marketing",
    "unsubscribe",
)

BLOCKED_DIRECTORY_DOMAINS = {"codet.ai", "codet.com"}
BLOCKED_DIRECTORY_NAMES = {"codet", "codet.ai"}


@dataclass
class CompanyContact:
    name: str
    domain: str
    region: str  # Karachi | Pakistan | MENA | Remote
    city: str
    emails: list[str] = field(default_factory=list)
    email_source: str = ""
    careers_url: str = ""
    sample_role: str = ""
    apply_url: str = ""


REGION_ORDER = {
    "Karachi": 0,
    "Pakistan": 1,
    "Qatar": 2,
    "Bahrain": 3,
    "Kuwait": 4,
    "Oman": 5,
    "UAE": 6,
    "KSA": 7,
    "Egypt": 8,
    "Jordan": 9,
    "Lebanon": 10,
    "MENA": 11,
    "Singapore": 12,
    "Malaysia": 13,
    "Europe": 14,
    "Australia": 15,
    "Remote": 16,
}


# Public software / product companies worth emailing from Karachi.
# known emails are only ones already published; sites are scraped for more.
COMPANY_DIRECTORY: tuple[tuple[str, str, str, str, tuple[str, ...]], ...] = (
    # Karachi
    ("10Pearls", "10pearls.com", "Karachi", "Karachi", ("careers@10pearls.com", "info@10pearls.com", "sahar.afzal@10pearls.com")),
    ("Folio3", "folio3.com", "Karachi", "Karachi", ()),
    ("VentureDive", "venturedive.com", "Karachi", "Karachi", ("careers@venturedive.com", "hr@venturedive.com")),
    ("Cubix", "cubix.co", "Karachi", "Karachi", ("hr@cubixlabs.com", "info@cubix.co")),
    ("Systems Limited", "systemsltd.com", "Karachi", "Karachi", ()),
    ("SadaPay", "sadapay.pk", "Karachi", "Karachi", ("careers@sadapay.pk", "hello@sadapay.pk")),
    ("Careem", "careem.com", "Karachi", "Karachi / Dubai", ("careers@careem.com",)),
    ("Ibex", "ibex.co", "Karachi", "Karachi", ()),
    ("Gaditek", "gaditek.com", "Karachi", "Karachi", ()),
    ("Tintash", "tintash.com", "Karachi", "Karachi", ()),
    ("Xgrid", "xgrid.co", "Karachi", "Karachi", ()),
    ("Bazaar Technologies", "bazaartech.com", "Karachi", "Karachi", ()),
    ("Retailo", "retailo.co", "Karachi", "Karachi", ()),
    ("Abhi", "abhi.com.pk", "Karachi", "Karachi", ()),
    ("NayaPay", "nayapay.com", "Karachi", "Karachi", ()),
    ("Bykea", "bykea.com", "Karachi", "Karachi", ()),
    ("Daraz", "daraz.pk", "Karachi", "Karachi", ()),
    ("Foodpanda Pakistan", "foodpanda.pk", "Karachi", "Karachi", ()),
    ("Zameen", "zameen.com", "Karachi", "Karachi", ()),
    ("PakWheels", "pakwheels.com", "Karachi", "Karachi", ()),
    ("Jazz", "jazz.com.pk", "Karachi", "Karachi", ()),
    ("Telenor Pakistan", "telenor.com.pk", "Karachi", "Karachi", ()),
    ("Contour Software", "contour-software.com", "Karachi", "Karachi", ()),
    ("Ovex Technologies", "ovextech.com", "Karachi", "Karachi", ()),
    ("Inbox Business Technologies", "inboxbiz.com", "Karachi", "Karachi", ()),
    ("TPS Worldwide", "tpsworldwide.com", "Karachi", "Karachi", ()),
    ("TRG Pakistan", "trgpakistan.com", "Karachi", "Karachi", ()),
    ("KalSoft", "kalsoft.com", "Karachi", "Karachi", ()),
    ("CureMD", "curemd.com", "Karachi", "Karachi", ()),
    ("NorthBay Solutions", "northbaysolutions.com", "Karachi", "Karachi", ()),
    ("Strategic Systems International", "ssidecisions.com", "Karachi", "Karachi", ()),
    ("Softech Worldwide", "softechworldwide.com", "Karachi", "Karachi", ()),
    ("Techlogix", "techlogix.com", "Karachi", "Karachi", ()),
    ("Salsoft Technologies", "salsoft.net", "Karachi", "Karachi", ()),
    ("Avanza Solutions", "avanzasolutions.com", "Karachi", "Karachi", ()),
    ("Dubizzle Pakistan / OLX", "olx.com.pk", "Karachi", "Karachi", ()),
    ("Sastaticket", "sastaticket.pk", "Karachi", "Karachi", ()),
    ("Trax", "trax.pk", "Karachi", "Karachi", ()),
    ("Keenu", "keenu.pk", "Karachi", "Karachi", ()),
    ("Haball", "haball.pk", "Karachi", "Karachi", ()),
    ("Afiniti", "afiniti.com", "Karachi", "Karachi / global", ()),
    ("Motive", "gomotive.com", "Karachi", "Karachi / remote", ("careers@gomotive.com",)),
    ("Securiti", "securiti.ai", "Karachi", "Karachi / remote", ()),
    ("Turing", "turing.com", "Karachi", "Remote / PK", ("careers@turing.com",)),
    # Rest of Pakistan (remote-friendly from Karachi)
    ("Arbisoft", "arbisoft.com", "Pakistan", "Lahore", ("contact@arbisoft.com",)),
    ("Confiz", "confiz.com", "Pakistan", "Lahore", ()),
    ("Devsinc", "devsinc.com", "Pakistan", "Lahore / Islamabad", ("sales@devsinc.com", "global.business@devsinc.com")),
    ("Emumba", "emumba.com", "Pakistan", "Islamabad", ()),
    ("Tkxel", "tkxel.com", "Pakistan", "Lahore", ()),
    ("Netsol", "netsoltech.com", "Pakistan", "Lahore", ()),
    ("Thoughtworks", "thoughtworks.com", "Pakistan", "PK / global", ("careers@thoughtworks.com",)),
    ("PureLogics", "purelogics.com", "Pakistan", "Lahore", ()),
    ("Dubizzle Labs", "dubizzlelabs.com", "Pakistan", "Lahore", ()),
    ("Nextbridge", "nextbridge.pk", "Pakistan", "Lahore", ()),
    ("Empiric", "empiric.com", "Pakistan", "Lahore", ()),
    ("Coderisti / Recur", "recur.com", "Pakistan", "Lahore", ()),
    # More Pakistani software / product / fintech (unique domains only)
    ("Arpatech", "arpatech.com", "Karachi", "Karachi", ()),
    ("Softech Systems", "softechsystems.com", "Karachi", "Karachi", ()),
    ("Mindstorm Studios", "mindstormstudios.com", "Karachi", "Karachi", ()),
    ("i2c", "i2cinc.com", "Karachi", "Karachi", ()),
    ("Vizteck Solutions", "vizteck.com", "Karachi", "Karachi", ()),
    ("Netsmartz", "netsmartz.com", "Pakistan", "Lahore", ()),
    ("Code Ninety", "codeninety.com", "Pakistan", "Islamabad", ()),
    ("Elixir Technologies", "elixirtech.com", "Pakistan", "Islamabad", ()),
    ("DPL", "dpl.com.pk", "Pakistan", "Islamabad", ()),
    ("Creative Chaos", "creativechaos.co", "Karachi", "Karachi", ()),
    ("KoderLabs", "koderlabs.com", "Karachi", "Karachi", ()),
    ("Rolustech", "rolustech.com", "Pakistan", "Lahore", ()),
    ("Sekel Technologies", "sekeltech.com", "Pakistan", "Lahore", ()),
    ("DevBatch", "devbatch.com", "Pakistan", "Lahore", ()),
    ("Techverx", "techverx.com", "Pakistan", "Lahore", ()),
    ("Speridian Technologies", "speridian.com", "Pakistan", "Islamabad", ()),
    ("Zigron", "zigron.com", "Pakistan", "Islamabad", ()),
    ("HazenTech", "hazentech.com", "Pakistan", "Islamabad", ()),
    ("Teknobuilt", "teknobuilt.com", "Pakistan", "Islamabad", ()),
    ("LMKT", "lmkt.com", "Pakistan", "Islamabad", ()),
    ("Nayatel", "nayatel.com", "Pakistan", "Islamabad", ()),
    ("StormFiber", "stormfiber.com", "Karachi", "Karachi", ()),
    ("Cybernet", "cyber.net.pk", "Karachi", "Karachi", ()),
    ("Engro", "engro.com", "Karachi", "Karachi", ()),
    ("HBL", "hbl.com", "Karachi", "Karachi", ()),
    ("UBL", "ubl.com.pk", "Karachi", "Karachi", ()),
    ("Meezan Bank", "meezanbank.com", "Karachi", "Karachi", ()),
    ("Bank Alfalah", "bankalfalah.com", "Karachi", "Karachi", ()),
    ("Allied Bank", "abl.com", "Pakistan", "Lahore", ()),
    ("MCB Bank", "mcb.com.pk", "Pakistan", "Lahore", ()),
    ("Faysal Bank", "faysalbank.com", "Karachi", "Karachi", ()),
    ("Askari Bank", "askaribank.com", "Pakistan", "Islamabad", ()),
    ("Easypaisa", "easypaisa.com.pk", "Pakistan", "Islamabad", ()),
    ("JazzCash", "jazzcash.com.pk", "Pakistan", "Islamabad", ()),
    ("Finja", "finja.pk", "Pakistan", "Lahore", ()),
    ("TRG World", "trgworld.com", "Karachi", "Karachi", ()),
    ("PriceOye", "priceoye.pk", "Pakistan", "Lahore", ()),
    ("Dawaai", "dawaai.pk", "Karachi", "Karachi", ()),
    ("Bookme", "bookme.pk", "Pakistan", "Lahore", ()),
    ("Telemart", "telemart.pk", "Karachi", "Karachi", ()),
    ("Shophive", "shophive.com", "Pakistan", "Lahore", ()),
    ("Symbios", "symbios.pk", "Karachi", "Karachi", ()),
    ("Homeshopping", "homeshopping.pk", "Karachi", "Karachi", ()),
    ("Swyft Logistics", "swyftlogistics.com", "Karachi", "Karachi", ()),
    ("M&P", "mulphilog.com", "Karachi", "Karachi", ()),
    ("TCS", "tcsexpress.com", "Karachi", "Karachi", ()),
    ("Rozee", "rozee.pk", "Karachi", "Karachi", ()),
    ("Mustakbil", "mustakbil.com", "Karachi", "Karachi", ()),
    ("BrightSpyre", "brightspyre.com", "Pakistan", "Islamabad", ()),
    ("Genetech Solutions", "genetechsolutions.com", "Karachi", "Karachi", ()),
    ("Powersoft19", "powersoft19.com", "Pakistan", "Lahore", ()),
    ("PTCL", "ptcl.com.pk", "Pakistan", "Islamabad", ()),
    ("Ufone", "ufone.com", "Pakistan", "Islamabad", ()),
    ("Zong CMPak", "zong.com.pk", "Pakistan", "Islamabad", ()),
    ("S&P Global Pakistan", "spglobal.com", "Pakistan", "Islamabad", ()),
    ("Folio3 UAE/PK", "folio3.ae", "MENA", "Dubai / Karachi", ()),
    # MENA product / software
    ("Talabat", "talabat.com", "MENA", "Dubai", ()),
    ("Delivery Hero", "deliveryhero.com", "MENA", "Dubai / Berlin", ("careers@deliveryhero.com",)),
    ("Noon", "noon.com", "MENA", "Dubai / Riyadh", ()),
    ("Tabby", "tabby.ai", "MENA", "Riyadh / Dubai", ()),
    ("Tamara", "tamara.co", "MENA", "Riyadh", ()),
    ("Property Finder", "propertyfinder.ae", "MENA", "Dubai", ()),
    ("Bayut", "bayut.com", "MENA", "Dubai", ()),
    ("Dubizzle Group", "dubizzle.com", "MENA", "Dubai", ()),
    ("Swvl", "swvl.com", "MENA", "Cairo / Dubai", ()),
    ("Kitopi", "kitopi.com", "MENA", "Dubai", ()),
    ("Unifonic", "unifonic.com", "MENA", "Riyadh", ()),
    ("Lean Technologies", "leantech.me", "MENA", "Riyadh", ()),
    ("Foodics", "foodics.com", "MENA", "Riyadh", ()),
    ("Salla", "salla.sa", "MENA", "Riyadh", ()),
    ("Zid", "zid.sa", "MENA", "Riyadh", ()),
    ("Jahez", "jahezgroup.com", "MENA", "Riyadh", ()),
    ("HungerStation", "hungerstation.com", "MENA", "Riyadh", ()),
    ("Paymob", "paymob.com", "MENA", "Cairo", ()),
    ("Fawry", "fawry.com", "MENA", "Cairo", ()),
    ("Instabug", "instabug.com", "MENA", "Cairo / remote", ()),
    ("Vezeeta", "vezeeta.com", "MENA", "Cairo", ()),
    ("MaxAB", "maxab.io", "MENA", "Cairo", ()),
    ("Anghami", "anghami.com", "MENA", "Beirut / Dubai", ()),
    ("Geidea", "geidea.net", "MENA", "Riyadh", ()),
    ("PayTabs", "paytabs.com", "MENA", "Riyadh / Bahrain", ()),
    ("HyperPay", "hyperpay.com", "MENA", "Riyadh", ()),
    ("STC", "stc.com.sa", "MENA", "Riyadh", ()),
    ("e& / Etisalat", "eand.com", "MENA", "Abu Dhabi", ()),
    ("Ooredoo", "ooredoo.com", "MENA", "Doha", ()),
    ("Emirates Group IT", "emirates.com", "MENA", "Dubai", ()),
    ("Qatar Airways IT", "qatarairways.com", "MENA", "Doha", ()),
    ("Wio Bank", "wio.io", "MENA", "Abu Dhabi", ()),
    ("Sarwa", "sarwa.co", "MENA", "Dubai", ()),
    ("Bayzat", "bayzat.com", "MENA", "Dubai", ()),
    ("Huspy", "huspy.com", "MENA", "Dubai", ()),
    ("Qlub", "qlub.io", "MENA", "Dubai", ()),
    ("Fresha", "fresha.com", "MENA", "Dubai / remote", ()),
    # Qatar
    ("Snoonu", "snoonu.com", "Qatar", "Doha / remote", ()),
    ("QCRI", "qcri.org", "Qatar", "Doha", ()),
    ("Malomatia", "malomatia.com", "Qatar", "Doha", ()),
    ("Meeza", "meeza.net", "Qatar", "Doha", ()),
    ("Vodafone Qatar", "vodafone.qa", "Qatar", "Doha", ()),
    ("QNB Digital", "qnb.com", "Qatar", "Doha", ()),
    ("BeIN Media Group", "bein.com", "Qatar", "Doha", ()),
    ("Al Jazeera Digital", "aljazeera.com", "Qatar", "Doha", ()),
    ("Ooredoo Money", "ooredoomoney.com", "Qatar", "Doha", ()),
    ("Mannai", "mannai.com", "Qatar", "Doha", ()),
    ("QatarEnergy Digital", "qatarenergy.qa", "Qatar", "Doha", ()),
    ("Sidra Medicine Digital", "sidra.org", "Qatar", "Doha", ()),
    ("HBKU / Qatar Foundation IT", "hbku.edu.qa", "Qatar", "Doha", ()),
    ("Commercial Bank Qatar", "cbq.qa", "Qatar", "Doha", ()),
    ("Doha Bank", "dohabank.com.qa", "Qatar", "Doha", ()),
    ("Masraf Al Rayan", "alrayan.com", "Qatar", "Doha", ()),
    ("Woqod", "woqod.com.qa", "Qatar", "Doha", ()),
    # Bahrain
    ("Benefit", "benefit.bh", "Bahrain", "Manama", ()),
    ("Beyon / Batelco", "beyon.com", "Bahrain", "Manama", ()),
    ("Batelco", "batelco.com", "Bahrain", "Manama", ()),
    ("stc Bahrain", "stc.com.bh", "Bahrain", "Manama", ()),
    ("Rain Bahrain", "rain.bh", "Bahrain", "Manama", ()),
    ("CrediMax", "credimax.com.bh", "Bahrain", "Manama", ()),
    ("Investcorp", "investcorp.com", "Bahrain", "Manama", ()),
    ("C5 Accelerate", "c5accelerate.com", "Bahrain", "Manama", ()),
    ("Tenmou", "tenmou.me", "Bahrain", "Manama", ()),
    ("Bahrain FinTech Bay", "bahrainfintechbay.com", "Bahrain", "Manama", ()),
    ("Almoayyed Computers", "almoayyed.com", "Bahrain", "Manama", ()),
    ("Fakhro Electronics", "fakhro.com", "Bahrain", "Manama", ()),
    ("Ithmaar Bank Digital", "ithmaarbank.com", "Bahrain", "Manama", ()),
    ("GFH Financial", "gfh.com", "Bahrain", "Manama", ()),
    ("BMMI Group Digital", "bmmi.com", "Bahrain", "Manama", ()),
    # Kuwait
    ("Zain", "zain.com", "Kuwait", "Kuwait / remote", ()),
    ("Tap Payments", "tap.company", "Kuwait", "Kuwait / remote", ()),
    ("MyFatoorah", "myfatoorah.com", "Kuwait", "Kuwait / Bahrain", ()),
    ("Boutiqaat", "boutiqaat.com", "Kuwait", "Kuwait", ()),
    ("Agility", "agility.com", "Kuwait", "Kuwait / remote", ()),
    ("NBK Digital", "nbk.com", "Kuwait", "Kuwait", ()),
    ("Kuwait Finance House", "kfh.com", "Kuwait", "Kuwait", ()),
    ("Gulf Bank", "e-gulfbank.com", "Kuwait", "Kuwait", ()),
    ("Zain Cash", "zaincash.iq", "Kuwait", "Kuwait / Iraq", ()),
    ("stc Kuwait", "stc.com.kw", "Kuwait", "Kuwait", ()),
    # Oman
    ("Omantel", "omantel.om", "Oman", "Muscat", ()),
    ("Ooredoo Oman", "ooredoo.om", "Oman", "Muscat", ()),
    ("Bank Muscat Digital", "bankmuscat.com", "Oman", "Muscat", ()),
    ("Awasr", "awasr.om", "Oman", "Muscat", ()),
    ("Oman Arab Bank Digital", "oman-arabbank.com", "Oman", "Muscat", ()),
    # UAE extra (remote-friendly product/AI)
    ("G42", "g42.ai", "UAE", "Abu Dhabi / remote", ()),
    ("Core42", "core42.ai", "UAE", "Abu Dhabi / remote", ()),
    ("Presight", "presight.ai", "UAE", "Abu Dhabi / remote", ()),
    ("Digital14", "digital14.com", "UAE", "Abu Dhabi", ()),
    ("Bayanat", "bayanat.ai", "UAE", "Abu Dhabi", ()),
    ("AIQ", "aiq.com", "UAE", "Abu Dhabi", ()),
    ("YAP", "yap.com", "UAE", "Dubai / remote", ()),
    ("Telr", "telr.com", "UAE", "Dubai / remote", ()),
    ("Network International", "network.global", "UAE", "Dubai", ()),
    ("Magnati", "magnati.com", "UAE", "Abu Dhabi", ()),
    ("Namshi", "namshi.com", "UAE", "Dubai", ()),
    ("Mumzworld", "mumzworld.com", "UAE", "Dubai", ()),
    ("Starzplay", "starzplay.com", "UAE", "Dubai / remote", ()),
    ("MBC Group / Shahid", "mbc.net", "UAE", "Dubai", ()),
    ("Cafu", "cafu.com", "UAE", "Dubai", ()),
    ("Botim", "botim.me", "UAE", "Dubai / remote", ()),
    ("Now Money", "nowmoney.me", "UAE", "Dubai / remote", ()),
    ("Checkout.com", "checkout.com", "UAE", "Dubai / remote", ("careers@checkout.com",)),
    ("Intertec Systems", "intertec.co", "UAE", "Dubai", ()),
    ("Emitac", "emitac.ae", "UAE", "Dubai", ()),
    ("Pure Harvest", "pureharvest.ae", "UAE", "Abu Dhabi", ()),
    ("Yellow Door Energy", "yellowdoorenergy.com", "UAE", "Dubai", ()),
    # KSA extra
    ("NEOM", "neom.com", "KSA", "NEOM / remote", ()),
    ("Elm", "elm.sa", "KSA", "Riyadh / remote", ()),
    ("Solutions by stc", "solutions.com.sa", "KSA", "Riyadh", ()),
    ("stc pay", "stcpay.com.sa", "KSA", "Riyadh", ()),
    ("Mrsool", "mrsool.co", "KSA", "Riyadh / remote", ()),
    ("The Chefz", "thechefz.co", "KSA", "Riyadh", ()),
    ("Nearpay", "nearpay.io", "KSA", "Riyadh / remote", ()),
    ("Moyasar", "moyasar.com", "KSA", "Riyadh / remote", ()),
    ("Zain KSA", "sa.zain.com", "KSA", "Riyadh", ()),
    ("Mobily", "mobily.com.sa", "KSA", "Riyadh", ()),
    ("Saudi Aramco Digital", "aramco.com", "KSA", "Dhahran", ()),
    ("SDAIA", "sdaia.gov.sa", "KSA", "Riyadh", ()),
    ("Red Sea Global", "redseaglobal.com", "KSA", "Jeddah / remote", ()),
    ("Qiddiya", "qiddiya.com", "KSA", "Riyadh", ()),
    ("ToYou", "toyou.io", "KSA", "Riyadh", ()),
    ("Ninja KSA", "ninja.sa", "KSA", "Riyadh", ()),
    # Egypt extra
    ("ITWorx", "itworx.com", "Egypt", "Cairo / remote", ()),
    ("Giza Systems", "gizasystems.com", "Egypt", "Cairo", ()),
    ("Link Development", "linkdev.com", "Egypt", "Cairo / remote", ()),
    ("Raya", "rayacorp.com", "Egypt", "Cairo", ()),
    ("Breadfast", "breadfast.com", "Egypt", "Cairo / remote", ()),
    ("Trella", "trella.app", "Egypt", "Cairo / remote", ()),
    ("Halan / MNT-Halan", "halan.com", "Egypt", "Cairo", ()),
    ("Vodafone Egypt", "vodafone.com.eg", "Egypt", "Cairo", ()),
    ("Valeo Egypt", "valeo.com", "Egypt", "Cairo / remote", ()),
    ("Elmenus", "elmenus.com", "Egypt", "Cairo", ()),
    ("Rabbit Mart", "rabbitmart.com", "Egypt", "Cairo", ()),
    ("Instant", "instant.com", "Egypt", "Cairo", ()),
    # More GCC / MENA product + software
    ("Beehive", "beehive.ae", "UAE", "Dubai / remote", ()),
    ("SmartCrowd", "smartcrowd.ae", "UAE", "Dubai", ()),
    ("PayBy", "payby.com", "UAE", "Dubai / remote", ()),
    ("Trukker", "trukker.com", "UAE", "Dubai / remote", ()),
    ("Shipa", "shipa.com", "UAE", "Dubai", ()),
    ("El Grocer", "elgrocer.com", "UAE", "Dubai", ()),
    ("Kibsons", "kibsons.com", "UAE", "Dubai", ()),
    ("Almosafer", "almosafer.com", "KSA", "Riyadh / remote", ()),
    ("Tajawal", "tajawal.com", "UAE", "Dubai / remote", ()),
    ("Sary", "sary.com", "KSA", "Riyadh / remote", ()),
    ("Lucidya", "lucidya.com", "KSA", "Riyadh / remote", ()),
    ("OpenSooq", "opensooq.com", "Jordan", "Amman / remote", ()),
    ("Abwaab", "abwaab.com", "Jordan", "Amman / remote", ()),
    ("Mawdoo3", "mawdoo3.com", "Jordan", "Amman / remote", ()),
    ("ArabiaWeather", "arabiaweather.com", "Jordan", "Amman", ()),
    ("ProgressSoft", "progressoft.com", "Jordan", "Amman / remote", ()),
    ("Estarta", "estarta.com", "Jordan", "Amman", ()),
    ("Murex", "murex.com", "Lebanon", "Beirut / remote", ()),
    ("Jawaker", "jawaker.com", "UAE", "Dubai / remote", ()),
    ("Rafeeq", "rafeeqapp.com", "Qatar", "Doha / remote", ()),
    ("Barakat", "barakatfresh.ae", "UAE", "Dubai", ()),
    ("Seera", "seera.sa", "KSA", "Riyadh", ()),
    ("Flynas Digital", "flynas.com", "KSA", "Riyadh", ()),
    ("QnE", "qne.com.sa", "KSA", "Riyadh", ()),
    ("Hala", "halacards.com", "KSA", "Riyadh / remote", ()),
    ("Tamkeen Technologies", "tamkeentech.sa", "KSA", "Riyadh", ()),
    ("Saudi Payments / mada", "saudipayments.com", "KSA", "Riyadh", ()),
    ("DSquares", "dsquares.com", "Egypt", "Cairo / remote", ()),
    ("Flat6Labs", "flat6labs.com", "Egypt", "Cairo / remote", ()),
    ("Incorta", "incorta.com", "Egypt", "Cairo / remote", ()),
    ("Synapse Analytics", "synapse-analytics.io", "Egypt", "Cairo / remote", ()),
    ("Bosta", "bosta.co", "Egypt", "Cairo / remote", ()),
    ("Telda", "telda.app", "Egypt", "Cairo / remote", ()),
    ("Money Fellows", "moneyfellows.com", "Egypt", "Cairo / remote", ()),
    ("Khazna", "khazna.app", "Egypt", "Cairo / remote", ()),
    ("Valify", "valify.me", "Egypt", "Cairo / remote", ()),
    ("Tarabut", "tarabut.com", "Bahrain", "Manama / remote", ()),
    ("NymCard", "nymcard.com", "UAE", "Abu Dhabi / remote", ()),
    ("Wahed", "wahed.com", "UAE", "Dubai / remote", ()),
    ("BitOasis", "bitoasis.net", "UAE", "Dubai / remote", ()),
    ("Cartlow", "cartlow.com", "UAE", "Dubai / remote", ()),
    ("Magnitt", "magnitt.com", "UAE", "Dubai / remote", ()),
    ("ZenHR", "zenhr.com", "Jordan", "Amman / remote", ()),
    ("MadfooatCom", "madfooat.com", "Jordan", "Amman / remote", ()),
    ("Nana", "nana.sa", "KSA", "Riyadh / remote", ()),
    ("Postpay", "postpay.io", "UAE", "Dubai / remote", ()),
    ("Soum", "soum.sa", "KSA", "Riyadh / remote", ()),
    ("Mostaql", "mostaql.com", "KSA", "Riyadh / remote", ()),
    ("RemotePass", "remotepass.com", "UAE", "Dubai / remote", ()),
    # Singapore / Malaysia / broader Asia remote-friendly targets
    ("Grab", "grab.com", "Singapore", "Singapore / remote", ()),
    ("Sea Group", "sea.com", "Singapore", "Singapore", ()),
    ("Shopee", "shopee.com", "Singapore", "Singapore / remote", ()),
    ("Carousell", "carousell.com", "Singapore", "Singapore / remote", ()),
    ("Nium", "nium.com", "Singapore", "Singapore / remote", ()),
    ("Aspire", "aspireapp.com", "Singapore", "Singapore / remote", ()),
    ("Endowus", "endowus.com", "Singapore", "Singapore", ()),
    ("Sleek", "sleek.com", "Singapore", "Singapore / remote", ()),
    ("PatSnap", "patsnap.com", "Singapore", "Singapore", ()),
    ("ShopBack", "shopback.com", "Singapore", "Singapore / remote", ()),
    ("Coda Payments", "codapayments.com", "Singapore", "Singapore", ()),
    ("Ninja Van", "ninjavan.co", "Singapore", "Singapore / remote", ()),
    ("Funding Societies", "fundingsocieties.com", "Singapore", "Singapore / remote", ()),
    ("Carro", "carro.co", "Singapore", "Singapore", ()),
    ("Foodpanda APAC", "foodpanda.com", "Singapore", "Singapore / remote", ()),
    ("Paktor", "paktor.com", "Singapore", "Singapore", ()),
    ("Carsome", "carsome.my", "Malaysia", "Kuala Lumpur / remote", ()),
    ("AirAsia Digital", "airasia.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Touch 'n Go Digital", "tngdigital.com.my", "Malaysia", "Kuala Lumpur", ()),
    ("Boost", "myboost.com.my", "Malaysia", "Kuala Lumpur", ()),
    ("GXBank", "gxbank.my", "Malaysia", "Kuala Lumpur", ()),
    ("MoneyLion Malaysia", "moneylion.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("iPay88", "ipay88.com", "Malaysia", "Kuala Lumpur", ()),
    ("Fave", "myfave.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("StoreHub", "storehub.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("EasyStore", "easystore.co", "Malaysia", "Kuala Lumpur / remote", ()),
    ("PitchIN", "pitchin.my", "Malaysia", "Kuala Lumpur", ()),
    ("Mudah", "mudah.my", "Malaysia", "Kuala Lumpur", ()),
    ("Teleport", "teleport.asia", "Malaysia", "Kuala Lumpur / remote", ()),
    ("JobStreet / SEEK Asia", "jobstreet.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Cars24 Gulf", "cars24.com", "UAE", "Dubai / remote", ()),
    ("Alaan", "alaan.com", "UAE", "Dubai / remote", ()),
    ("Qashio", "qashio.com", "UAE", "Dubai / remote", ()),
    # Extra UAE / Dubai remote-friendly startups
    ("Tabby", "tabby.ai", "UAE", "Dubai / remote", ()),
    ("Spotii", "spotii.com", "UAE", "Dubai / remote", ()),
    ("Lean Technologies", "leantech.me", "UAE", "Dubai / remote", ()),
    ("Tarabut Gateway", "tarabut.com", "UAE", "Dubai / Bahrain / remote", ()),
    ("Mamo Pay", "mamopay.com", "UAE", "Dubai / remote", ()),
    ("Pyypl", "pyypl.com", "UAE", "Dubai / remote", ()),
    ("Ziina", "ziina.com", "UAE", "Dubai / remote", ()),
    ("Property Finder", "propertyfinder.ae", "UAE", "Dubai / remote", ()),
    ("Bayut", "bayut.com", "UAE", "Dubai / remote", ()),
    ("Dubizzle", "dubizzle.com", "UAE", "Dubai / remote", ()),
    ("Kitopi", "kitopi.com", "UAE", "Dubai / remote", ()),
    ("Vezeeta", "vezeeta.com", "MENA", "Cairo / Dubai / remote", ()),
    ("Syarah", "syarah.com", "KSA", "Riyadh / remote", ()),
    ("Jahez", "jahez.net", "KSA", "Riyadh / remote", ()),
    ("HungerStation", "hungerstation.com", "KSA", "Riyadh / remote", ()),
    ("Unifonic", "unifonic.com", "KSA", "Riyadh / remote", ()),
    ("Foodics", "foodics.com", "KSA", "Riyadh / remote", ()),
    ("PayTabs", "paytabs.com", "KSA", "Riyadh / remote", ()),
    ("HyperPay", "hyperpay.com", "KSA", "Riyadh / remote", ()),
    ("Geidea", "geidea.net", "KSA", "Riyadh / remote", ()),
    ("Rasan", "rasan.co", "KSA", "Riyadh / remote", ()),
    ("Tameeni", "tameeni.com", "KSA", "Riyadh / remote", ()),
    ("STC Bank", "stcbank.com.sa", "KSA", "Riyadh / remote", ()),
    ("Noon", "noon.com", "UAE", "Dubai / Riyadh / remote", ()),
    # Kuwait / Bahrain remote-friendly
    ("Boubyan Digital", "boubyan.com", "Kuwait", "Kuwait City", ()),
    ("Zain Kuwait Digital", "kw.zain.com", "Kuwait", "Kuwait City", ()),
    ("Ooredoo Kuwait", "ooredoo.com.kw", "Kuwait", "Kuwait City", ()),
    ("Talabat", "talabat.com", "MENA", "Kuwait / Dubai / remote", ()),
    ("Benefit Company", "benefit.bh", "Bahrain", "Manama / remote", ()),
    ("Rain Bahrain", "rain.bh", "Bahrain", "Manama / remote", ()),
    # Extra Singapore remote-friendly startups
    ("Fazz", "fazz.com", "Singapore", "Singapore / remote", ()),
    ("MatchMove", "matchmove.com", "Singapore", "Singapore / remote", ()),
    ("Tech in Asia", "techinasia.com", "Singapore", "Singapore / remote", ()),
    ("Glints", "glints.com", "Singapore", "Singapore / remote", ()),
    ("Hubble.sg", "hubble.sg", "Singapore", "Singapore / remote", ()),
    ("StaffAny", "staffany.com", "Singapore", "Singapore / remote", ()),
    ("Oddle", "oddle.me", "Singapore", "Singapore / remote", ()),
    ("Secretlab", "secretlab.co", "Singapore", "Singapore / remote", ()),
    ("Razer", "razer.com", "Singapore", "Singapore / remote", ()),
    # Extra Malaysia remote-friendly startups
    ("iPrice Group", "ipricegroup.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("PolicyStreet", "policystreet.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Kakitangan.com", "kakitangan.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Shopee MY", "shopee.com.my", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Lazada MY", "lazada.com.my", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Monday.com", "monday.com", "MENA", "Tel Aviv / remote", ()),
    ("Wix", "wix.com", "MENA", "Tel Aviv / remote", ()),
    ("Fiverr", "fiverr.com", "MENA", "Tel Aviv / remote", ()),
    ("Similarweb", "similarweb.com", "MENA", "Tel Aviv / remote", ()),
    ("AppsFlyer", "appsflyer.com", "MENA", "Tel Aviv / remote", ()),
    ("Riskified", "riskified.com", "MENA", "Tel Aviv / remote", ()),
    ("Melio", "meliopayments.com", "MENA", "Tel Aviv / remote", ()),
    ("Lightricks", "lightricks.com", "MENA", "Jerusalem / remote", ()),
    ("Tipalti", "tipalti.com", "MENA", "Tel Aviv / remote", ()),
    # Europe — remote-friendly product / software (not US mega-corps)
    ("Monzo", "monzo.com", "Europe", "London / remote", ()),
    ("Revolut", "revolut.com", "Europe", "London / remote", ()),
    ("Wise", "wise.com", "Europe", "London / remote", ()),
    ("Starling Bank", "starlingbank.com", "Europe", "London / remote", ()),
    ("GoCardless", "gocardless.com", "Europe", "London / remote", ()),
    ("OakNorth", "oaknorth.com", "Europe", "London / remote", ()),
    ("Tide", "tide.co", "Europe", "London / remote", ()),
    ("Curve", "curve.com", "Europe", "London / remote", ()),
    ("Paddle", "paddle.com", "Europe", "London / remote", ()),
    ("Thought Machine", "thoughtmachine.net", "Europe", "London / remote", ()),
    ("Featurespace", "featurespace.com", "Europe", "Cambridge / remote", ()),
    ("Tractable", "tractable.ai", "Europe", "London / remote", ()),
    ("Faculty", "faculty.ai", "Europe", "London / remote", ()),
    ("Darktrace", "darktrace.com", "Europe", "Cambridge / remote", ()),
    ("Skyscanner", "skyscanner.net", "Europe", "Edinburgh / remote", ()),
    ("Trainline", "thetrainline.com", "Europe", "London / remote", ()),
    ("Deliveroo", "deliveroo.com", "Europe", "London / remote", ()),
    ("Just Eat Takeaway", "justeattakeaway.com", "Europe", "London / Amsterdam / remote", ()),
    ("SumUp", "sumup.com", "Europe", "London / remote", ()),
    ("Cleo", "meetcleo.com", "Europe", "London / remote", ()),
    ("Marshmallow", "marshmallow.com", "Europe", "London / remote", ()),
    ("Zepz", "zepz.com", "Europe", "London / remote", ()),
    ("Rapyd", "rapyd.net", "Europe", "London / remote", ()),
    ("Contentful", "contentful.com", "Europe", "Berlin / remote", ()),
    ("Personio", "personio.com", "Europe", "Munich / remote", ()),
    ("Celonis", "celonis.com", "Europe", "Munich / remote", ()),
    ("N26", "n26.com", "Europe", "Berlin / remote", ()),
    ("Trade Republic", "traderepublic.com", "Europe", "Berlin / remote", ()),
    ("Flix", "flix.com", "Europe", "Munich / remote", ()),
    ("GetYourGuide", "getyourguide.com", "Europe", "Berlin / remote", ()),
    ("SoundCloud", "soundcloud.com", "Europe", "Berlin / remote", ()),
    ("Zalando", "zalando.com", "Europe", "Berlin / remote", ()),
    ("HelloFresh", "hellofresh.com", "Europe", "Berlin / remote", ()),
    ("AUTO1", "auto1-group.com", "Europe", "Berlin / remote", ()),
    ("Wefox", "wefox.com", "Europe", "Berlin / remote", ()),
    ("Miro", "miro.com", "Europe", "Amsterdam / remote", ()),
    ("Adyen", "adyen.com", "Europe", "Amsterdam / remote", ()),
    ("Mollie", "mollie.com", "Europe", "Amsterdam / remote", ()),
    ("Bird", "bird.com", "Europe", "Amsterdam / remote", ()),
    ("TomTom", "tomtom.com", "Europe", "Amsterdam / remote", ()),
    ("WeTransfer", "wetransfer.com", "Europe", "Amsterdam / remote", ()),
    ("Picnic", "picnic.app", "Europe", "Amsterdam / remote", ()),
    ("Bunq", "bunq.com", "Europe", "Amsterdam / remote", ()),
    ("Backbase", "backbase.com", "Europe", "Amsterdam / remote", ()),
    ("Criteo", "criteo.com", "Europe", "Paris / remote", ()),
    ("Doctolib", "doctolib.com", "Europe", "Paris / remote", ()),
    ("BlaBlaCar", "blablacar.com", "Europe", "Paris / remote", ()),
    ("Ledger", "ledger.com", "Europe", "Paris / remote", ()),
    ("Contentsquare", "contentsquare.com", "Europe", "Paris / remote", ()),
    ("Deezer", "deezer.com", "Europe", "Paris / remote", ()),
    ("Alan", "alan.com", "Europe", "Paris / remote", ()),
    ("Qonto", "qonto.com", "Europe", "Paris / remote", ()),
    ("Spendesk", "spendesk.com", "Europe", "Paris / remote", ()),
    ("Dataiku", "dataiku.com", "Europe", "Paris / remote", ()),
    ("Mistral AI", "mistral.ai", "Europe", "Paris / remote", ()),
    ("Photoroom", "photoroom.com", "Europe", "Paris / remote", ()),
    ("Swile", "swile.co", "Europe", "Paris / remote", ()),
    ("ManoMano", "manomano.com", "Europe", "Paris / remote", ()),
    ("Back Market", "backmarket.com", "Europe", "Paris / remote", ()),
    ("Scaleway", "scaleway.com", "Europe", "Paris / remote", ()),
    ("OVHcloud", "ovhcloud.com", "Europe", "Roubaix / remote", ()),
    ("Shift Technology", "shift-technology.com", "Europe", "Paris / remote", ()),
    ("Glovo", "glovoapp.com", "Europe", "Barcelona / remote", ()),
    ("Cabify", "cabify.com", "Europe", "Madrid / remote", ()),
    ("Factorial", "factorialhr.com", "Europe", "Barcelona / remote", ()),
    ("Typeform", "typeform.com", "Europe", "Barcelona / remote", ()),
    ("TravelPerk", "travelperk.com", "Europe", "Barcelona / remote", ()),
    ("Wallapop", "wallapop.com", "Europe", "Barcelona / remote", ()),
    ("Jobandtalent", "jobandtalent.com", "Europe", "Madrid / remote", ()),
    ("Adevinta", "adevinta.com", "Europe", "Barcelona / remote", ()),
    # Spain — more remote-friendly product startups
    ("Holded", "holded.com", "Europe", "Barcelona / remote", ()),
    ("CoverManager", "covermanager.com", "Europe", "Seville / remote", ()),
    ("Habitissimo", "habitissimo.com", "Europe", "Palma / remote", ()),
    ("Badi", "badi.com", "Europe", "Barcelona / remote", ()),
    ("Fever", "feverup.com", "Europe", "Madrid / remote", ()),
    ("Idealista", "idealista.com", "Europe", "Madrid / remote", ()),
    ("Bizum", "bizum.es", "Europe", "Madrid / remote", ()),
    ("Sequra", "sequra.com", "Europe", "Barcelona / remote", ()),
    ("Capchase", "capchase.com", "Europe", "Madrid / remote", ()),
    ("Genially", "genial.ly", "Europe", "Cordoba / remote", ()),
    ("Ironhack", "ironhack.com", "Europe", "Madrid / Barcelona / remote", ()),
    ("Clarity AI", "clarity.ai", "Europe", "Madrid / remote", ()),
    # Italy — remote-friendly product / fintech startups
    ("Satispay", "satispay.com", "Europe", "Milan / remote", ()),
    ("Scalapay", "scalapay.com", "Europe", "Milan / remote", ()),
    ("Bending Spoons", "bendingspoons.com", "Europe", "Milan / remote", ()),
    ("Musixmatch", "musixmatch.com", "Europe", "Bologna / remote", ()),
    ("Prima Assicurazioni", "prima.it", "Europe", "Milan / remote", ()),
    ("Facile.it", "facile.it", "Europe", "Milan / remote", ()),
    ("MutuiOnline", "mutuionline.it", "Europe", "Milan / remote", ()),
    ("Moneyfarm", "moneyfarm.com", "Europe", "Milan / remote", ()),
    ("Yolo Group", "yolo-insurance.com", "Europe", "Milan / remote", ()),
    ("Casavo", "casavo.com", "Europe", "Milan / remote", ()),
    ("Cortilia", "cortilia.it", "Europe", "Milan / remote", ()),
    ("Milkman Technologies", "milkmantechnologies.com", "Europe", "Milan / remote", ()),
    ("Young Platform", "youngplatform.com", "Europe", "Turin / remote", ()),
    ("Conio", "conio.com", "Europe", "Milan / remote", ()),
    ("Everli", "everli.com", "Europe", "Milan / remote", ()),
    ("Helbiz", "helbiz.com", "Europe", "Milan / remote", ()),
    ("DoveVado / Moovit IT", "moovit.com", "Europe", "Italy / remote", ()),
    ("Fiscozen", "fiscozen.it", "Europe", "Milan / remote", ()),
    ("TeamSystem", "teamsystem.com", "Europe", "Pesaro / remote", ()),
    ("Buzzoole", "buzzoole.com", "Europe", "Naples / remote", ()),
    ("Contents.com", "contents.com", "Europe", "Milan / remote", ()),
    ("VueStorefront / Alokai", "alokai.com", "Europe", "Italy / remote", ()),
    ("Farfetch", "farfetch.com", "Europe", "Porto / remote", ()),
    ("OutSystems", "outsystems.com", "Europe", "Lisbon / remote", ()),
    ("Feedzai", "feedzai.com", "Europe", "Lisbon / remote", ()),
    ("Remote", "remote.com", "Europe", "Lisbon / remote", ()),
    ("Talkdesk", "talkdesk.com", "Europe", "Lisbon / remote", ()),
    ("Unbabel", "unbabel.com", "Europe", "Lisbon / remote", ()),
    ("Intercom", "intercom.com", "Europe", "Dublin / remote", ()),
    ("Teamwork", "teamwork.com", "Europe", "Cork / remote", ()),
    ("Fenergo", "fenergo.com", "Europe", "Dublin / remote", ()),
    ("Flipdish", "flipdish.com", "Europe", "Dublin / remote", ()),
    ("Klarna", "klarna.com", "Europe", "Stockholm / remote", ()),
    ("Zettle", "zettle.com", "Europe", "Stockholm / remote", ()),
    ("Epidemic Sound", "epidemicsound.com", "Europe", "Stockholm / remote", ()),
    ("Trustpilot", "trustpilot.com", "Europe", "Copenhagen / remote", ()),
    ("Lunar", "lunar.app", "Europe", "Copenhagen / remote", ()),
    ("Pleo", "pleo.io", "Europe", "Copenhagen / remote", ()),
    ("Too Good To Go", "toogoodtogo.com", "Europe", "Copenhagen / remote", ()),
    ("Wolt", "wolt.com", "Europe", "Helsinki / remote", ()),
    ("Aiven", "aiven.io", "Europe", "Helsinki / remote", ()),
    ("Smartly", "smartly.io", "Europe", "Helsinki / remote", ()),
    ("RELEX", "relexsolutions.com", "Europe", "Helsinki / remote", ()),
    ("Supermetrics", "supermetrics.com", "Europe", "Helsinki / remote", ()),
    ("ICEYE", "iceye.com", "Europe", "Helsinki / remote", ()),
    ("Bolt", "bolt.eu", "Europe", "Tallinn / remote", ()),
    ("Pipedrive", "pipedrive.com", "Europe", "Tallinn / remote", ()),
    ("Veriff", "veriff.com", "Europe", "Tallinn / remote", ()),
    ("Kahoot", "kahoot.com", "Europe", "Oslo / remote", ()),
    ("Cognite", "cognite.com", "Europe", "Oslo / remote", ()),
    ("Visma", "visma.com", "Europe", "Oslo / remote", ()),
    ("Xeneta", "xeneta.com", "Europe", "Oslo / remote", ()),
    ("Oda", "oda.com", "Europe", "Oslo / remote", ()),
    ("Proton", "proton.me", "Europe", "Geneva / remote", ()),
    ("Nexthink", "nexthink.com", "Europe", "Lausanne / remote", ()),
    ("Scandit", "scandit.com", "Europe", "Zurich / remote", ()),
    ("Bitdefender", "bitdefender.com", "Europe", "Bucharest / remote", ()),
    ("eMAG", "emag.ro", "Europe", "Bucharest / remote", ()),
    ("Preply", "preply.com", "Europe", "Kyiv / remote", ()),
    ("Ajax Systems", "ajax.systems", "Europe", "Kyiv / remote", ()),
    ("Doist", "doist.com", "Europe", "Europe / remote", ()),
    ("Toggl", "toggl.com", "Europe", "Tallinn / remote", ()),
    ("Hotjar", "hotjar.com", "Europe", "Malta / remote", ()),
    ("GitBook", "gitbook.com", "Europe", "Europe / remote", ()),
    ("Cal.com", "cal.com", "Europe", "Europe / remote", ()),
    ("Plausible", "plausible.io", "Europe", "Europe / remote", ("hello@plausible.io",)),
    ("Strapi", "strapi.io", "Europe", "Paris / remote", ()),
    ("Framer", "framer.com", "Europe", "Amsterdam / remote", ()),
    ("JetBrains", "jetbrains.com", "Europe", "Prague / remote", ()),
    ("Gitpod", "gitpod.io", "Europe", "Europe / remote", ()),
    ("Bunny.net", "bunny.net", "Europe", "Slovenia / remote", ()),
    ("Dynatrace", "dynatrace.com", "Europe", "Linz / remote", ()),
    ("Grafana Labs", "grafana.com", "Europe", "Europe / remote", ()),
    ("DeepL", "deepl.com", "Europe", "Cologne / remote", ()),
    ("Aleph Alpha", "aleph-alpha.com", "Europe", "Heidelberg / remote", ()),
    ("Stability AI", "stability.ai", "Europe", "London / remote", ()),
    ("ElevenLabs", "elevenlabs.io", "Europe", "London / remote", ()),
    ("Synthesia", "synthesia.io", "Europe", "London / remote", ()),
    ("Nextcloud", "nextcloud.com", "Europe", "Stuttgart / remote", ()),
    ("Hetzner", "hetzner.com", "Europe", "Germany / remote", ()),
    ("Leapsome", "leapsome.com", "Europe", "Berlin / remote", ()),
    ("HiBob", "hibob.com", "Europe", "London / remote", ()),
    ("Oyster", "oysterhr.com", "Europe", "Europe / remote", ()),
    ("SafetyWing", "safetywing.com", "Europe", "Europe / remote", ()),
    ("PostHog", "posthog.com", "Europe", "Europe / remote", ()),
    ("Langfuse", "langfuse.com", "Europe", "Berlin / remote", ()),
    ("Ghost", "ghost.org", "Europe", "Singapore / remote", ()),
    ("Element", "element.io", "Europe", "London / remote", ()),
    ("Prismic", "prismic.io", "Europe", "Paris / remote", ()),
    ("PayFit", "payfit.com", "Europe", "Paris / remote", ()),
    ("Payhawk", "payhawk.com", "Europe", "London / remote", ()),
    ("TransferGo", "transfergo.com", "Europe", "Vilnius / remote", ()),
    ("Trading 212", "trading212.com", "Europe", "London / remote", ()),
    ("eToro", "etoro.com", "Europe", "London / remote", ()),
    ("Bitstamp", "bitstamp.net", "Europe", "Luxembourg / remote", ()),
    ("Bitpanda", "bitpanda.com", "Europe", "Vienna / remote", ()),
    ("Nexo", "nexo.com", "Europe", "Sofia / remote", ()),
    ("Trezor", "trezor.io", "Europe", "Prague / remote", ()),
    ("Pennylane", "pennylane.com", "Europe", "Paris / remote", ()),
    ("Algolia", "algolia.com", "Europe", "Paris / remote", ()),
    ("Storyblok", "storyblok.com", "Europe", "Linz / remote", ()),
    ("Meilisearch", "meilisearch.com", "Europe", "Paris / remote", ()),
    ("deepset", "deepset.ai", "Europe", "Berlin / remote", ()),
    ("Weaviate", "weaviate.io", "Europe", "Amsterdam / remote", ()),
    ("Qdrant", "qdrant.tech", "Europe", "Berlin / remote", ()),
    ("Dashlane", "dashlane.com", "Europe", "Paris / remote", ()),
    ("Tuta", "tuta.com", "Europe", "Hannover / remote", ()),
    ("Tresorit", "tresorit.com", "Europe", "Zurich / remote", ()),
    ("pCloud", "pcloud.com", "Europe", "Sofia / remote", ()),
    ("Nord Security", "nordsecurity.com", "Europe", "Vilnius / remote", ()),
    ("Mullvad", "mullvad.net", "Europe", "Gothenburg / remote", ()),
    ("Vivaldi", "vivaldi.com", "Europe", "Oslo / remote", ()),
    ("Ecosia", "ecosia.org", "Europe", "Berlin / remote", ()),
    ("Qwant", "qwant.com", "Europe", "Paris / remote", ()),
    ("Supabase", "supabase.com", "Remote", "Worldwide remote", ()),
    ("Neon", "neon.tech", "Remote", "Worldwide remote", ()),
    ("Directus", "directus.io", "Remote", "Worldwide remote", ()),
    ("Appwrite", "appwrite.io", "Remote", "Worldwide remote", ()),
    ("Sentry", "sentry.io", "Remote", "Worldwide remote", ()),
    ("Silal", "silal.ae", "UAE", "Abu Dhabi / remote", ()),
    ("Cequens", "cequens.com", "Egypt", "Cairo / remote", ()),
    ("BambooHR", "bamboohr.com", "Remote", "Worldwide remote", ()),
    ("Zapier", "zapier.com", "Remote", "Worldwide remote", ()),
    ("Buffer", "buffer.com", "Remote", "Worldwide remote", ()),
    ("Basecamp", "basecamp.com", "Remote", "Worldwide remote", ()),
    ("Help Scout", "helpscout.com", "Remote", "Worldwide remote", ()),
    ("Close", "close.com", "Remote", "Worldwide remote", ()),
    ("ConvertKit", "convertkit.com", "Remote", "Worldwide remote", ()),
    ("Beehiiv", "beehiiv.com", "Remote", "Worldwide remote", ()),
    ("Substack", "substack.com", "Remote", "Worldwide remote", ()),
    ("Linear", "linear.app", "Remote", "Worldwide remote", ()),
    ("Raycast", "raycast.com", "Remote", "Worldwide remote", ()),
    ("Notion", "notion.so", "Remote", "Worldwide remote", ()),
    ("Coda", "coda.io", "Remote", "Worldwide remote", ()),
    ("Retool", "retool.com", "Remote", "Worldwide remote", ()),
    ("Hasura", "hasura.io", "Remote", "Worldwide remote", ()),
    ("PlanetScale", "planetscale.com", "Remote", "Worldwide remote", ()),
    ("Railway", "railway.app", "Remote", "Worldwide remote", ()),
    ("Render", "render.com", "Remote", "Worldwide remote", ()),
    ("Fly.io", "fly.io", "Remote", "Worldwide remote", ()),
    ("Clerk", "clerk.com", "Remote", "Worldwide remote", ()),
    ("WorkOS", "workos.com", "Remote", "Worldwide remote", ()),
    ("Resend", "resend.com", "Remote", "Worldwide remote", ()),
    ("Loops", "loops.so", "Remote", "Worldwide remote", ()),
    ("Tally", "tally.so", "Europe", "Europe / remote", ()),
    ("Lemlist", "lemlist.com", "Europe", "Paris / remote", ()),
    ("Swan", "swan.io", "Europe", "Paris / remote", ()),
    ("Mirakl", "mirakl.com", "Europe", "Paris / remote", ()),
    ("Voodoo", "voodoo.io", "Europe", "Paris / remote", ()),
    ("Sorare", "sorare.com", "Europe", "Paris / remote", ()),
    ("Pigment", "pigment.com", "Europe", "Paris / remote", ()),
    ("Front", "front.com", "Europe", "Paris / remote", ()),
    ("Aircall", "aircall.io", "Europe", "Paris / remote", ()),
    ("Gorgias", "gorgias.com", "Europe", "Paris / remote", ()),
    ("Shippeo", "shippeo.com", "Europe", "Paris / remote", ()),
    ("Lydia", "lydia-app.com", "Europe", "Paris / remote", ()),
    ("Shine", "shine.fr", "Europe", "Paris / remote", ()),
    ("Doctrine", "doctrine.fr", "Europe", "Paris / remote", ()),
    ("Welcome to the Jungle", "welcometothejungle.com", "Europe", "Paris / remote", ()),
    ("Truecaller", "truecaller.com", "Europe", "Stockholm / remote", ()),
    ("Voi", "voi.com", "Europe", "Stockholm / remote", ()),
    ("Kry", "kry.se", "Europe", "Stockholm / remote", ()),
    ("Trustly", "trustly.com", "Europe", "Stockholm / remote", ()),
    ("King", "king.com", "Europe", "Stockholm / remote", ()),
    ("Spotify", "spotify.com", "Europe", "Stockholm / remote", ()),
    ("Booking.com", "booking.com", "Europe", "Amsterdam / remote", ()),
    ("Coolblue", "coolblue.nl", "Europe", "Rotterdam / remote", ()),
    ("Bol.com", "bol.com", "Europe", "Utrecht / remote", ()),
    ("UiPath", "uipath.com", "Europe", "Bucharest / remote", ()),
    ("Grammarly", "grammarly.com", "Europe", "Kyiv / remote", ()),
    ("BrowserStack", "browserstack.com", "Remote", "Worldwide remote", ()),
    ("Freshworks", "freshworks.com", "Remote", "Worldwide remote", ()),
    ("Zoho", "zoho.com", "Remote", "Worldwide remote", ()),
    ("Chargebee", "chargebee.com", "Remote", "Worldwide remote", ()),
    ("Razorpay", "razorpay.com", "Remote", "Worldwide remote", ()),
    ("Postman", "postman.com", "Remote", "Worldwide remote", ()),
    ("Apollo.io", "apollo.io", "Remote", "Worldwide remote", ()),
    ("Clay", "clay.com", "Remote", "Worldwide remote", ()),
    ("Attio", "attio.com", "Europe", "London / remote", ()),
    ("Ashby", "ashbyhq.com", "Remote", "Worldwide remote", ()),
    ("Rippling", "rippling.com", "Remote", "Worldwide remote", ()),
    ("Deel", "deel.com", "Remote", "Worldwide remote", ()),
    ("Hopin", "hopin.com", "Europe", "London / remote", ()),
    ("Onfido", "onfido.com", "Europe", "London / remote", ()),
    ("FlixBus", "flixbus.com", "Europe", "Munich / remote", ()),
    # Extra remote / SEA / Europe targets for more strict-valid volume
    ("Lovable", "lovable.dev", "Remote", "Worldwide remote", ()),
    ("Replicate", "replicate.com", "Remote", "Worldwide remote", ()),
    ("Modal", "modal.com", "Remote", "Worldwide remote", ()),
    ("Tinybird", "tinybird.co", "Remote", "Worldwide remote", ()),
    ("Inngest", "inngest.com", "Remote", "Worldwide remote", ()),
    ("Trigger.dev", "trigger.dev", "Remote", "Worldwide remote", ()),
    ("Liveblocks", "liveblocks.io", "Remote", "Worldwide remote", ()),
    ("Tiptap", "tiptap.dev", "Remote", "Worldwide remote", ()),
    ("Novu", "novu.co", "Remote", "Worldwide remote", ()),
    ("Dub.co", "dub.co", "Remote", "Worldwide remote", ()),
    ("OpenStatus", "openstatus.dev", "Remote", "Worldwide remote", ()),
    ("Formbricks", "formbricks.com", "Remote", "Worldwide remote", ()),
    ("Twenty", "twenty.com", "Remote", "Worldwide remote", ()),
    ("Plane", "plane.so", "Remote", "Worldwide remote", ()),
    ("AppSmith", "appsmith.com", "Remote", "Worldwide remote", ()),
    ("Tooljet", "tooljet.com", "Remote", "Worldwide remote", ()),
    ("Budibase", "budibase.com", "Remote", "Worldwide remote", ()),
    ("NocoDB", "nocodb.com", "Remote", "Worldwide remote", ()),
    ("Baserow", "baserow.io", "Remote", "Worldwide remote", ()),
    ("Outline", "getoutline.com", "Remote", "Worldwide remote", ()),
    ("Standard Notes", "standardnotes.com", "Remote", "Worldwide remote", ()),
    ("Bitwarden", "bitwarden.com", "Remote", "Worldwide remote", ()),
    ("1Password", "1password.com", "Remote", "Worldwide remote", ()),
    ("Tailscale", "tailscale.com", "Remote", "Worldwide remote", ()),
    ("Fastly", "fastly.com", "Remote", "Worldwide remote", ()),
    ("Netlify", "netlify.com", "Remote", "Worldwide remote", ()),
    ("HashiCorp", "hashicorp.com", "Remote", "Worldwide remote", ()),
    ("Datadog", "datadoghq.com", "Remote", "Worldwide remote", ()),
    ("New Relic", "newrelic.com", "Remote", "Worldwide remote", ()),
    ("PagerDuty", "pagerduty.com", "Remote", "Worldwide remote", ()),
    ("Split.io", "split.io", "Remote", "Worldwide remote", ()),
    ("Amplitude", "amplitude.com", "Remote", "Worldwide remote", ()),
    ("Mixpanel", "mixpanel.com", "Remote", "Worldwide remote", ()),
    ("Heap", "heap.io", "Remote", "Worldwide remote", ()),
    ("FullStory", "fullstory.com", "Remote", "Worldwide remote", ()),
    ("Crisp", "crisp.chat", "Remote", "Worldwide remote", ()),
    ("Chatwoot", "chatwoot.com", "Remote", "Worldwide remote", ()),
    ("Plain.com", "plain.com", "Remote", "Worldwide remote", ()),
    ("incident.io", "incident.io", "Remote", "Worldwide remote", ()),
    ("Rootly", "rootly.com", "Remote", "Worldwide remote", ()),
    ("FireHydrant", "firehydrant.com", "Remote", "Worldwide remote", ()),
    ("Chronosphere", "chronosphere.io", "Remote", "Worldwide remote", ()),
    ("Honeycomb", "honeycomb.io", "Remote", "Worldwide remote", ()),
    ("Sourcegraph", "sourcegraph.com", "Remote", "Worldwide remote", ()),
    ("Codecov", "codecov.io", "Remote", "Worldwide remote", ()),
    ("SonarSource", "sonarsource.com", "Europe", "Geneva / remote", ()),
    ("Gitea", "gitea.com", "Remote", "Worldwide remote", ()),
    ("Exoscale", "exoscale.com", "Europe", "Lausanne / remote", ()),
    ("UpCloud", "upcloud.com", "Europe", "Helsinki / remote", ()),
    ("Vultr", "vultr.com", "Remote", "Worldwide remote", ()),
    ("DigitalOcean", "digitalocean.com", "Remote", "Worldwide remote", ()),
    ("Linode", "linode.com", "Remote", "Worldwide remote", ()),
    ("Cloudinary", "cloudinary.com", "Remote", "Worldwide remote", ()),
    ("Imgix", "imgix.com", "Remote", "Worldwide remote", ()),
    ("Mux", "mux.com", "Remote", "Worldwide remote", ()),
    ("LiveKit", "livekit.io", "Remote", "Worldwide remote", ()),
    ("Agora", "agora.io", "Remote", "Worldwide remote", ()),
    ("Twilio", "twilio.com", "Remote", "Worldwide remote", ()),
    ("Mailgun", "mailgun.com", "Remote", "Worldwide remote", ()),
    ("Postmark", "postmarkapp.com", "Remote", "Worldwide remote", ()),
    ("Customer.io", "customer.io", "Remote", "Worldwide remote", ()),
    ("Braze", "braze.com", "Remote", "Worldwide remote", ()),
    ("OneSignal", "onesignal.com", "Remote", "Worldwide remote", ()),
    ("CleverTap", "clevertap.com", "Remote", "Worldwide remote", ()),
    ("MoEngage", "moengage.com", "Remote", "Worldwide remote", ()),
    ("Webflow", "webflow.com", "Remote", "Worldwide remote", ()),
    ("Bubble", "bubble.io", "Remote", "Worldwide remote", ()),
    ("Softr", "softr.io", "Remote", "Worldwide remote", ()),
    ("Glide", "glideapps.com", "Remote", "Worldwide remote", ()),
    ("ClickUp", "clickup.com", "Remote", "Worldwide remote", ()),
    ("Asana", "asana.com", "Remote", "Worldwide remote", ()),
    ("Height", "height.app", "Remote", "Worldwide remote", ()),
    ("Shortcut", "shortcut.com", "Remote", "Worldwide remote", ()),
    ("Figma", "figma.com", "Remote", "Worldwide remote", ()),
    ("Whimsical", "whimsical.com", "Remote", "Worldwide remote", ()),
    ("Excalidraw", "excalidraw.com", "Remote", "Worldwide remote", ()),
    ("tldraw", "tldraw.com", "Remote", "Worldwide remote", ()),
    ("Canva", "canva.com", "Remote", "Sydney / remote", ()),
    ("Fivetran", "fivetran.com", "Remote", "Worldwide remote", ()),
    ("dbt Labs", "getdbt.com", "Remote", "Worldwide remote", ()),
    ("Airbyte", "airbyte.com", "Remote", "Worldwide remote", ()),
    ("Census", "getcensus.com", "Remote", "Worldwide remote", ()),
    ("Hightouch", "hightouch.com", "Remote", "Worldwide remote", ()),
    ("Segment", "segment.com", "Remote", "Worldwide remote", ()),
    ("RudderStack", "rudderstack.com", "Remote", "Worldwide remote", ()),
    ("Snowplow", "snowplow.io", "Europe", "London / remote", ()),
    ("Metabase", "metabase.com", "Remote", "Worldwide remote", ()),
    ("Preset", "preset.io", "Remote", "Worldwide remote", ()),
    ("Hex", "hex.tech", "Remote", "Worldwide remote", ()),
    ("Mode Analytics", "mode.com", "Remote", "Worldwide remote", ()),
    ("Observable", "observablehq.com", "Remote", "Worldwide remote", ()),
    ("AssemblyAI", "assemblyai.com", "Remote", "Worldwide remote", ()),
    ("Speechmatics", "speechmatics.com", "Europe", "Cambridge / remote", ()),
    ("RunPod", "runpod.io", "Remote", "Worldwide remote", ()),
    ("Together AI", "together.ai", "Remote", "Worldwide remote", ()),
    ("Fireworks AI", "fireworks.ai", "Remote", "Worldwide remote", ()),
    ("Anyscale", "anyscale.com", "Remote", "Worldwide remote", ()),
    ("Weights & Biases", "wandb.ai", "Remote", "Worldwide remote", ()),
    ("Comet ML", "comet.com", "Remote", "Worldwide remote", ()),
    ("Labelbox", "labelbox.com", "Remote", "Worldwide remote", ()),
    ("Snorkel AI", "snorkel.ai", "Remote", "Worldwide remote", ()),
    ("Lago", "getlago.com", "Europe", "Paris / remote", ()),
    ("Orb", "withorb.com", "Remote", "Worldwide remote", ()),
    ("Metronome", "metronome.com", "Remote", "Worldwide remote", ()),
    ("Plaid", "plaid.com", "Remote", "Worldwide remote", ()),
    ("Marqeta", "marqeta.com", "Remote", "Worldwide remote", ()),
    ("Unit Finance", "unit.co", "Remote", "Worldwide remote", ()),
    ("Column", "column.com", "Remote", "Worldwide remote", ()),
    ("Modern Treasury", "moderntreasury.com", "Remote", "Worldwide remote", ()),
    ("Increase", "increase.com", "Remote", "Worldwide remote", ()),
    ("Nubank", "nubank.com.br", "Remote", "Sao Paulo / remote", ()),
    ("Xendit", "xendit.co", "Remote", "Jakarta / Singapore / remote", ()),
    ("Midtrans", "midtrans.com", "Remote", "Jakarta / remote", ()),
    ("Traveloka", "traveloka.com", "Remote", "Jakarta / remote", ()),
    ("GoTo", "gotocompany.com", "Remote", "Jakarta / remote", ()),
    ("Tokopedia", "tokopedia.com", "Remote", "Jakarta / remote", ()),
    ("Bukalapak", "bukalapak.com", "Remote", "Jakarta / remote", ()),
    ("Ajaib", "ajaib.co.id", "Remote", "Jakarta / remote", ()),
    ("Stockbit", "stockbit.com", "Remote", "Jakarta / remote", ()),
    ("Lazada", "lazada.com", "Singapore", "Singapore / remote", ()),
    ("Zalora", "zalora.com", "Singapore", "Singapore / remote", ()),
    ("PropertyGuru", "propertyguru.com", "Singapore", "Singapore / remote", ()),
    ("Circles.Life", "circles.life", "Singapore", "Singapore / remote", ()),
    ("Advance.AI", "advance.ai", "Singapore", "Singapore / remote", ()),
    ("StraitsX", "straitsx.com", "Singapore", "Singapore / remote", ()),
    ("Validus", "validus.sg", "Singapore", "Singapore / remote", ()),
    ("FinAccel", "finaccel.com", "Singapore", "Singapore / remote", ()),
    ("BigPay", "bigpayme.com", "Malaysia", "Kuala Lumpur / remote", ()),
    ("Lalamove", "lalamove.com", "Remote", "Hong Kong / remote", ()),
    ("Klook", "klook.com", "Remote", "Hong Kong / remote", ()),
    ("PhonePe", "phonepe.com", "Remote", "India / remote", ()),
    ("CRED", "cred.club", "Remote", "India / remote", ()),
    ("Groww", "groww.in", "Remote", "India / remote", ()),
    ("Zerodha", "zerodha.com", "Remote", "India / remote", ()),
    ("Meesho", "meesho.com", "Remote", "India / remote", ()),
    ("Swiggy", "swiggy.com", "Remote", "India / remote", ()),
    ("Zomato", "zomato.com", "Remote", "India / remote", ()),
    ("ShareChat", "sharechat.com", "Remote", "India / remote", ()),
    ("Dream11", "dream11.com", "Remote", "India / remote", ()),
    ("Druva", "druva.com", "Remote", "India / remote", ()),
    ("Icertis", "icertis.com", "Remote", "India / remote", ()),
    ("Persistent", "persistent.com", "Remote", "India / remote", ()),
    # --- Expansion: Pakistan software / product (physical OK) ---
    ("Sofizar", "sofizar.com", "Pakistan", "Lahore", ()),
    ("SoftPyramid", "softpyramid.com", "Pakistan", "Lahore", ()),
    ("WebHR", "webhr.co", "Pakistan", "Lahore / remote", ()),
    ("VTeams", "vteams.com", "Pakistan", "Lahore / remote", ()),
    ("CyberVision", "cybervisiontech.com", "Pakistan", "Islamabad", ()),
    ("Arrivy", "arrivy.com", "Pakistan", "Lahore / remote", ()),
    ("Markaz", "markaz.app", "Pakistan", "Lahore / remote", ()),
    ("Softinlays", "softinlays.com", "Pakistan", "Lahore", ()),
    ("Logicose", "logicose.com", "Pakistan", "Lahore", ()),
    ("Appxolute", "appxolute.com", "Pakistan", "Islamabad", ()),
    ("Dastgyr", "dastgyr.com", "Karachi", "Karachi", ()),
    ("Tez Financial Services", "tezfinancialservices.com", "Pakistan", "Lahore", ()),
    ("Golootlo", "golootlo.pk", "Karachi", "Karachi", ()),
    ("Synergy-IT", "synergy-it.com", "Pakistan", "Lahore", ()),
    ("Softsquare", "softsquare.biz", "Pakistan", "Lahore", ()),
    ("TechVista Systems", "techvistasystems.com", "Pakistan", "Lahore", ()),
    ("SoftAct", "softact.com", "Pakistan", "Islamabad", ()),
    ("Folio3 Digital", "folio3.com", "Pakistan", "Lahore / Karachi", ()),
    ("Devsinc Labs", "devsinc.com", "Pakistan", "Lahore / Islamabad", ()),
    ("Codehouse", "codehouse.pk", "Pakistan", "Islamabad", ()),
    ("Techverce", "techverce.com", "Pakistan", "Lahore", ()),
    ("Devathon", "devathon.com", "Pakistan", "Lahore / remote", ()),
    ("Codility Solutions", "codilitysolutions.com", "Pakistan", "Lahore", ()),
    ("ApexSoft", "apexsoft.net", "Pakistan", "Lahore", ()),
    ("FolioSoft", "foliosoft.com", "Pakistan", "Lahore", ()),
    ("CresTech", "crestechsoftware.com", "Pakistan", "Lahore", ()),
    ("Ebryx", "ebryx.com", "Pakistan", "Lahore / remote", ()),
    ("Fermat Commerce", "fermatcommerce.com", "Pakistan", "Lahore / remote", ()),
    ("Retailistan", "retailistan.com", "Karachi", "Karachi", ()),
    ("Cartlow PK", "cartlow.com", "Pakistan", "Lahore / remote", ()),
    ("PriceOye Tech", "priceoye.pk", "Pakistan", "Lahore", ()),
    ("Bookme Tech", "bookme.pk", "Pakistan", "Lahore", ()),
    ("Rozee Tech", "rozee.pk", "Karachi", "Karachi", ()),
    ("Mustakbil Tech", "mustakbil.com", "Karachi", "Karachi", ()),
    ("BrightSpyre Tech", "brightspyre.com", "Pakistan", "Islamabad", ()),
    ("LMKT Digital", "lmkt.com", "Pakistan", "Islamabad", ()),
    ("Nayatel Digital", "nayatel.com", "Pakistan", "Islamabad", ()),
    ("StormFiber Digital", "stormfiber.com", "Karachi", "Karachi", ()),
    ("Cybernet Digital", "cyber.net.pk", "Karachi", "Karachi", ()),
    ("PTCL Digital", "ptcl.com.pk", "Pakistan", "Islamabad", ()),
    ("Jazz Digital", "jazz.com.pk", "Karachi", "Karachi", ()),
    ("Telenor Digital", "telenor.com.pk", "Karachi", "Karachi", ()),
    ("Ufone Digital", "ufone.com", "Pakistan", "Islamabad", ()),
    ("Zong Digital", "zong.com.pk", "Pakistan", "Islamabad", ()),
    ("Easypaisa Tech", "easypaisa.com.pk", "Pakistan", "Islamabad", ()),
    ("JazzCash Tech", "jazzcash.com.pk", "Pakistan", "Islamabad", ()),
    ("Finja Tech", "finja.pk", "Pakistan", "Lahore", ()),
    ("HBL Tech", "hbl.com", "Karachi", "Karachi", ()),
    ("UBL Tech", "ubl.com.pk", "Karachi", "Karachi", ()),
    ("Meezan Tech", "meezanbank.com", "Karachi", "Karachi", ()),
    ("Bank Alfalah Tech", "bankalfalah.com", "Karachi", "Karachi", ()),
    ("BankIslami Digital", "bankislami.com.pk", "Karachi", "Karachi", ()),
    ("JS Bank Digital", "jsbl.com", "Karachi", "Karachi", ()),
    ("Soneri Bank Digital", "soneribank.com", "Karachi", "Karachi", ()),
    ("Silkbank Digital", "silkbank.com.pk", "Karachi", "Karachi", ()),
    ("DIB Pakistan Digital", "dibpak.com", "Karachi", "Karachi", ()),
    ("S&P Global PK Tech", "spglobal.com", "Pakistan", "Islamabad", ()),
    ("i2c Pakistan", "i2cinc.com", "Karachi", "Karachi", ()),
    ("CureMD Pakistan", "curemd.com", "Karachi", "Karachi", ()),
    ("Afiniti Pakistan", "afiniti.com", "Karachi", "Karachi / global", ()),
    ("Ibex Pakistan", "ibex.co", "Karachi", "Karachi", ()),
    ("Gaditek Pakistan", "gaditek.com", "Karachi", "Karachi", ()),
    ("Tintash Pakistan", "tintash.com", "Karachi", "Karachi", ()),
    ("Xgrid Pakistan", "xgrid.co", "Karachi", "Karachi", ()),
    ("Securiti Pakistan", "securiti.ai", "Karachi", "Karachi / remote", ()),
    ("Motive Pakistan", "gomotive.com", "Karachi", "Karachi / remote", ()),
    ("Turing Pakistan", "turing.com", "Karachi", "Remote / PK", ()),
    ("Thoughtworks Pakistan", "thoughtworks.com", "Pakistan", "PK / global", ()),
    ("Careem Pakistan", "careem.com", "Karachi", "Karachi / Dubai", ()),
    ("SadaPay Pakistan", "sadapay.pk", "Karachi", "Karachi", ()),
    ("10Pearls Pakistan", "10pearls.com", "Karachi", "Karachi", ()),
    ("VentureDive Pakistan", "venturedive.com", "Karachi", "Karachi", ()),
    ("Cubix Pakistan", "cubix.co", "Karachi", "Karachi", ()),
    ("Systems Limited Pakistan", "systemsltd.com", "Karachi", "Karachi", ()),
    ("Arbisoft Pakistan", "arbisoft.com", "Pakistan", "Lahore", ()),
    ("Confiz Pakistan", "confiz.com", "Pakistan", "Lahore", ()),
    ("Emumba Pakistan", "emumba.com", "Pakistan", "Islamabad", ()),
    ("Tkxel Pakistan", "tkxel.com", "Pakistan", "Lahore", ()),
    ("Netsol Pakistan", "netsoltech.com", "Pakistan", "Lahore", ()),
    ("PureLogics Pakistan", "purelogics.com", "Pakistan", "Lahore", ()),
    ("Dubizzle Labs Pakistan", "dubizzlelabs.com", "Pakistan", "Lahore", ()),
    ("Nextbridge Pakistan", "nextbridge.pk", "Pakistan", "Lahore", ()),
    ("Empiric Pakistan", "empiric.com", "Pakistan", "Lahore", ()),
    ("Coderisti Pakistan", "recur.com", "Pakistan", "Lahore", ()),
    ("Arpatech Pakistan", "arpatech.com", "Karachi", "Karachi", ()),
    ("Softech Systems Pakistan", "softechsystems.com", "Karachi", "Karachi", ()),
    ("Mindstorm Pakistan", "mindstormstudios.com", "Karachi", "Karachi", ()),
    ("Vizteck Pakistan", "vizteck.com", "Karachi", "Karachi", ()),
    ("Netsmartz Pakistan", "netsmartz.com", "Pakistan", "Lahore", ()),
    ("Code Ninety Pakistan", "codeninety.com", "Pakistan", "Islamabad", ()),
    ("Elixir Pakistan", "elixirtech.com", "Pakistan", "Islamabad", ()),
    ("DPL Pakistan", "dpl.com.pk", "Pakistan", "Islamabad", ()),
    ("Creative Chaos Pakistan", "creativechaos.co", "Karachi", "Karachi", ()),
    ("KoderLabs Pakistan", "koderlabs.com", "Karachi", "Karachi", ()),
    ("Rolustech Pakistan", "rolustech.com", "Pakistan", "Lahore", ()),
    ("Sekel Pakistan", "sekeltech.com", "Pakistan", "Lahore", ()),
    ("DevBatch Pakistan", "devbatch.com", "Pakistan", "Lahore", ()),
    ("Techverx Pakistan", "techverx.com", "Pakistan", "Lahore", ()),
    ("Speridian Pakistan", "speridian.com", "Pakistan", "Islamabad", ()),
    ("Zigron Pakistan", "zigron.com", "Pakistan", "Islamabad", ()),
    ("HazenTech Pakistan", "hazentech.com", "Pakistan", "Islamabad", ()),
    ("Teknobuilt Pakistan", "teknobuilt.com", "Pakistan", "Islamabad", ()),
    ("Genetech Pakistan", "genetechsolutions.com", "Karachi", "Karachi", ()),
    ("Powersoft19 Pakistan", "powersoft19.com", "Pakistan", "Lahore", ()),
    ("NorthBay Pakistan", "northbaysolutions.com", "Karachi", "Karachi", ()),
    ("SSI Pakistan", "ssidecisions.com", "Karachi", "Karachi", ()),
    ("Softech Worldwide Pakistan", "softechworldwide.com", "Karachi", "Karachi", ()),
    ("Techlogix Pakistan", "techlogix.com", "Karachi", "Karachi", ()),
    ("Salsoft Pakistan", "salsoft.net", "Karachi", "Karachi", ()),
    ("Avanza Pakistan", "avanzasolutions.com", "Karachi", "Karachi", ()),
    ("KalSoft Pakistan", "kalsoft.com", "Karachi", "Karachi", ()),
    ("TPS Pakistan", "tpsworldwide.com", "Karachi", "Karachi", ()),
    ("TRG Pakistan Tech", "trgpakistan.com", "Karachi", "Karachi", ()),
    ("Inbox Pakistan", "inboxbiz.com", "Karachi", "Karachi", ()),
    ("Ovex Pakistan", "ovextech.com", "Karachi", "Karachi", ()),
    ("Contour Pakistan", "contour-software.com", "Karachi", "Karachi", ()),
    ("Folio3 Karachi", "folio3.com", "Karachi", "Karachi", ()),
    ("Bazaar Pakistan", "bazaartech.com", "Karachi", "Karachi", ()),
    ("Retailo Pakistan", "retailo.co", "Karachi", "Karachi", ()),
    ("Abhi Pakistan", "abhi.com.pk", "Karachi", "Karachi", ()),
    ("NayaPay Pakistan", "nayapay.com", "Karachi", "Karachi", ()),
    ("Bykea Pakistan", "bykea.com", "Karachi", "Karachi", ()),
    ("Daraz Pakistan", "daraz.pk", "Karachi", "Karachi", ()),
    ("Foodpanda Pakistan Tech", "foodpanda.pk", "Karachi", "Karachi", ()),
    ("Zameen Tech", "zameen.com", "Karachi", "Karachi", ()),
    ("PakWheels Tech", "pakwheels.com", "Karachi", "Karachi", ()),
    ("OLX Pakistan Tech", "olx.com.pk", "Karachi", "Karachi", ()),
    ("Sastaticket Tech", "sastaticket.pk", "Karachi", "Karachi", ()),
    ("Trax Tech", "trax.pk", "Karachi", "Karachi", ()),
    ("Keenu Tech", "keenu.pk", "Karachi", "Karachi", ()),
    ("Haball Tech", "haball.pk", "Karachi", "Karachi", ()),
    ("Dawaai Tech", "dawaai.pk", "Karachi", "Karachi", ()),
    ("Telemart Tech", "telemart.pk", "Karachi", "Karachi", ()),
    ("Shophive Tech", "shophive.com", "Pakistan", "Lahore", ()),
    ("Homeshopping Tech", "homeshopping.pk", "Karachi", "Karachi", ()),
    ("Symbios Tech", "symbios.pk", "Karachi", "Karachi", ()),
    ("Swyft Tech", "swyftlogistics.com", "Karachi", "Karachi", ()),
    ("M&P Tech", "mulphilog.com", "Karachi", "Karachi", ()),
    ("TCS Tech", "tcsexpress.com", "Karachi", "Karachi", ()),
    ("Engro Tech", "engro.com", "Karachi", "Karachi", ()),
    ("TRG World Tech", "trgworld.com", "Karachi", "Karachi", ()),
    ("Folio3 UAE Tech", "folio3.ae", "MENA", "Dubai / Karachi", ()),
    # --- Expansion: Kuwait ---
    ("UPayments", "upayments.com", "Kuwait", "Kuwait / remote", ()),
    ("SkipCash", "skipcash.com", "Kuwait", "Kuwait / remote", ()),
    ("Xcite Alghanim", "xcite.com", "Kuwait", "Kuwait", ()),
    ("Warba Bank Digital", "warbabank.com", "Kuwait", "Kuwait", ()),
    ("KIB Digital", "kib.com.kw", "Kuwait", "Kuwait", ()),
    ("Burgan Bank Digital", "burgan.com", "Kuwait", "Kuwait", ()),
    ("Jazeera Airways Digital", "jazeeraairways.com", "Kuwait", "Kuwait", ()),
    ("Kuwait Airways Digital", "kuwaitairways.com", "Kuwait", "Kuwait", ()),
    ("CBK Digital", "cbk.com", "Kuwait", "Kuwait", ()),
    ("KAMCO Invest Digital", "kamcoinvest.com", "Kuwait", "Kuwait", ()),
    ("Markaz Kuwait", "markaz.com", "Kuwait", "Kuwait", ()),
    ("Alghanim Industries Digital", "alghanim.com", "Kuwait", "Kuwait", ()),
    ("Equate Digital", "equate.com", "Kuwait", "Kuwait", ()),
    ("Ooredoo Kuwait Digital", "ooredoo.com.kw", "Kuwait", "Kuwait City", ()),
    ("Zain Kuwait Tech", "kw.zain.com", "Kuwait", "Kuwait City", ()),
    ("stc Kuwait Tech", "stc.com.kw", "Kuwait", "Kuwait", ()),
    ("Boubyan Tech", "boubyan.com", "Kuwait", "Kuwait City", ()),
    ("NBK Kuwait Tech", "nbk.com", "Kuwait", "Kuwait", ()),
    ("KFH Tech", "kfh.com", "Kuwait", "Kuwait", ()),
    ("Gulf Bank Tech", "e-gulfbank.com", "Kuwait", "Kuwait", ()),
    ("Tap Payments Kuwait", "tap.company", "Kuwait", "Kuwait / remote", ()),
    ("MyFatoorah Kuwait", "myfatoorah.com", "Kuwait", "Kuwait / Bahrain", ()),
    ("Boutiqaat Kuwait", "boutiqaat.com", "Kuwait", "Kuwait", ()),
    ("Agility Kuwait", "agility.com", "Kuwait", "Kuwait / remote", ()),
    ("Zain Group Tech", "zain.com", "Kuwait", "Kuwait / remote", ()),
    ("Zain Cash Tech", "zaincash.iq", "Kuwait", "Kuwait / Iraq", ()),
    # --- Expansion: Qatar ---
    ("iHorizons", "ihorizons.com", "Qatar", "Doha / remote", ()),
    ("Qatar Islamic Bank Digital", "qib.com.qa", "Qatar", "Doha", ()),
    ("Dukhan Bank Digital", "dukhanbank.com", "Qatar", "Doha", ()),
    ("Ahli Bank Qatar Digital", "ahlibank.com.qa", "Qatar", "Doha", ()),
    ("QIIB Digital", "qiib.com.qa", "Qatar", "Doha", ()),
    ("Hamad Medical Digital", "hamad.qa", "Qatar", "Doha", ()),
    ("Msheireb Properties Digital", "msheireb.com", "Qatar", "Doha", ()),
    ("Estithmar Holding Digital", "estithmarholding.com", "Qatar", "Doha", ()),
    ("GWC Digital", "gwclogistics.com", "Qatar", "Doha", ()),
    ("QTerminals Digital", "qterminals.qa", "Qatar", "Doha", ()),
    ("Mwani Qatar Digital", "mwani.com.qa", "Qatar", "Doha", ()),
    ("Qatar Post Digital", "qatarpost.qa", "Qatar", "Doha", ()),
    ("Aspire Zone Digital", "aspirezone.qa", "Qatar", "Doha", ()),
    ("Barwa Digital", "barwa.com.qa", "Qatar", "Doha", ()),
    ("UDC Digital", "udcqatar.com", "Qatar", "Doha", ()),
    ("Qatari Diar Digital", "qataridiar.com", "Qatar", "Doha", ()),
    ("Snoonu Qatar", "snoonu.com", "Qatar", "Doha / remote", ()),
    ("Rafeeq Qatar", "rafeeqapp.com", "Qatar", "Doha / remote", ()),
    ("Ooredoo Qatar Tech", "ooredoo.com", "Qatar", "Doha", ()),
    ("Qatar Airways Tech", "qatarairways.com", "Qatar", "Doha", ()),
    ("QNB Tech", "qnb.com", "Qatar", "Doha", ()),
    ("BeIN Tech", "bein.com", "Qatar", "Doha", ()),
    ("Al Jazeera Tech", "aljazeera.com", "Qatar", "Doha", ()),
    ("Malomatia Tech", "malomatia.com", "Qatar", "Doha", ()),
    ("Meeza Tech", "meeza.net", "Qatar", "Doha", ()),
    ("Vodafone Qatar Tech", "vodafone.qa", "Qatar", "Doha", ()),
    ("Mannai Tech", "mannai.com", "Qatar", "Doha", ()),
    ("QatarEnergy Tech", "qatarenergy.qa", "Qatar", "Doha", ()),
    ("Sidra Tech", "sidra.org", "Qatar", "Doha", ()),
    ("HBKU Tech", "hbku.edu.qa", "Qatar", "Doha", ()),
    ("Commercial Bank Qatar Tech", "cbq.qa", "Qatar", "Doha", ()),
    ("Doha Bank Tech", "dohabank.com.qa", "Qatar", "Doha", ()),
    ("Masraf Al Rayan Tech", "alrayan.com", "Qatar", "Doha", ()),
    ("Woqod Tech", "woqod.com.qa", "Qatar", "Doha", ()),
    ("Ooredoo Money Qatar", "ooredoomoney.com", "Qatar", "Doha", ()),
    ("QCRI Tech", "qcri.org", "Qatar", "Doha", ()),
    # --- Expansion: Australia remote-friendly product / software ---
    ("Canva AU", "canva.com", "Australia", "Sydney / remote", ()),
    ("Atlassian", "atlassian.com", "Australia", "Sydney / remote", ()),
    ("Culture Amp", "cultureamp.com", "Australia", "Melbourne / remote", ()),
    ("SafetyCulture", "safetyculture.com", "Australia", "Sydney / remote", ()),
    ("Deputy", "deputy.com", "Australia", "Sydney / remote", ()),
    ("Employment Hero", "employmenthero.com", "Australia", "Sydney / remote", ()),
    ("Linktree", "linktr.ee", "Australia", "Melbourne / remote", ()),
    ("Immutable", "immutable.com", "Australia", "Sydney / remote", ()),
    ("Airwallex", "airwallex.com", "Australia", "Melbourne / remote", ()),
    ("Envato", "envato.com", "Australia", "Melbourne / remote", ()),
    ("Campaign Monitor", "campaignmonitor.com", "Australia", "Sydney / remote", ()),
    ("REA Group", "rea-group.com", "Australia", "Melbourne / remote", ()),
    ("SEEK", "seek.com.au", "Australia", "Melbourne / remote", ()),
    ("Carsales", "carsales.com.au", "Australia", "Melbourne / remote", ()),
    ("Domain Group", "domain.com.au", "Australia", "Sydney / remote", ()),
    ("Tyro", "tyro.com", "Australia", "Sydney / remote", ()),
    ("Zip Co", "zip.co", "Australia", "Sydney / remote", ()),
    ("Afterpay", "afterpay.com", "Australia", "Melbourne / remote", ()),
    ("Brighte", "brighte.com.au", "Australia", "Sydney / remote", ()),
    ("Expert360", "expert360.com", "Australia", "Sydney / remote", ()),
    ("Hipages", "hipages.com.au", "Australia", "Sydney / remote", ()),
    ("Airtasker", "airtasker.com", "Australia", "Sydney / remote", ()),
    ("Buildkite", "buildkite.com", "Australia", "Melbourne / remote", ()),
    ("Prospa", "prospa.com", "Australia", "Sydney / remote", ()),
    ("Judo Bank", "judo.bank", "Australia", "Melbourne / remote", ()),
    ("Up Banking", "up.com.au", "Australia", "Melbourne / remote", ()),
    ("Wisetech Global", "wisetechglobal.com", "Australia", "Sydney / remote", ()),
    ("TechnologyOne", "technologyonecorp.com", "Australia", "Brisbane / remote", ()),
    ("NextDC", "nextdc.com", "Australia", "Sydney / remote", ()),
    ("SiteMinder", "siteminder.com", "Australia", "Sydney / remote", ()),
    ("Rokt", "rokt.com", "Australia", "Sydney / remote", ()),
    ("Finder", "finder.com.au", "Australia", "Sydney / remote", ()),
    ("Xero AU", "xero.com", "Australia", "Melbourne / remote", ()),
    ("MYOB", "myob.com", "Australia", "Melbourne / remote", ()),
    ("Culture Amp AU", "cultureamp.com", "Australia", "Melbourne / remote", ()),
    ("SafetyCulture AU", "safetyculture.com", "Australia", "Sydney / remote", ()),
    ("Deputy AU", "deputy.com", "Australia", "Sydney / remote", ()),
    ("Employment Hero AU", "employmenthero.com", "Australia", "Sydney / remote", ()),
    ("Linktree AU", "linktr.ee", "Australia", "Melbourne / remote", ()),
    ("Immutable AU", "immutable.com", "Australia", "Sydney / remote", ()),
    ("Airwallex AU", "airwallex.com", "Australia", "Melbourne / remote", ()),
    ("Canva Australia", "canva.com", "Australia", "Sydney / remote", ()),
    ("Atlassian AU", "atlassian.com", "Australia", "Sydney / remote", ()),
    ("Envato AU", "envato.com", "Australia", "Melbourne / remote", ()),
    ("Campaign Monitor AU", "campaignmonitor.com", "Australia", "Sydney / remote", ()),
    ("REA Group AU", "rea-group.com", "Australia", "Melbourne / remote", ()),
    ("SEEK AU", "seek.com.au", "Australia", "Melbourne / remote", ()),
    ("Carsales AU", "carsales.com.au", "Australia", "Melbourne / remote", ()),
    ("Domain AU", "domain.com.au", "Australia", "Sydney / remote", ()),
    ("Tyro AU", "tyro.com", "Australia", "Sydney / remote", ()),
    ("Zip AU", "zip.co", "Australia", "Sydney / remote", ()),
    ("Afterpay AU", "afterpay.com", "Australia", "Melbourne / remote", ()),
    ("Brighte AU", "brighte.com.au", "Australia", "Sydney / remote", ()),
    ("Expert360 AU", "expert360.com", "Australia", "Sydney / remote", ()),
    ("Hipages AU", "hipages.com.au", "Australia", "Sydney / remote", ()),
    ("Airtasker AU", "airtasker.com", "Australia", "Sydney / remote", ()),
    ("Buildkite AU", "buildkite.com", "Australia", "Melbourne / remote", ()),
    ("Prospa AU", "prospa.com", "Australia", "Sydney / remote", ()),
    ("Judo Bank AU", "judo.bank", "Australia", "Melbourne / remote", ()),
    ("Up Banking AU", "up.com.au", "Australia", "Melbourne / remote", ()),
    ("Wisetech AU", "wisetechglobal.com", "Australia", "Sydney / remote", ()),
    ("TechnologyOne AU", "technologyonecorp.com", "Australia", "Brisbane / remote", ()),
    ("NextDC AU", "nextdc.com", "Australia", "Sydney / remote", ()),
    ("SiteMinder AU", "siteminder.com", "Australia", "Sydney / remote", ()),
    ("Rokt AU", "rokt.com", "Australia", "Sydney / remote", ()),
    ("Finder AU", "finder.com.au", "Australia", "Sydney / remote", ()),
    ("Xero Australia", "xero.com", "Australia", "Melbourne / remote", ()),
    ("MYOB AU", "myob.com", "Australia", "Melbourne / remote", ()),
    # --- Expansion: Europe + MENA startups (fresh domains) ---
    ("Soldo", "soldo.com", "Europe", "London / remote", ()),
    ("Moss", "getmoss.com", "Europe", "Berlin / remote", ()),
    ("Mambu", "mambu.com", "Europe", "Amsterdam / remote", ()),
    ("Solaris", "solarisgroup.com", "Europe", "Berlin / remote", ()),
    ("Vivid Money", "vivid.money", "Europe", "Berlin / remote", ()),
    ("Bux", "getbux.com", "Europe", "Amsterdam / remote", ()),
    ("Plum", "withplum.com", "Europe", "London / remote", ()),
    ("Moneybox", "moneyboxapp.com", "Europe", "London / remote", ()),
    ("Octopus Energy", "octopus.energy", "Europe", "London / remote", ()),
    ("Gousto", "gousto.co.uk", "Europe", "London / remote", ()),
    ("Flink", "goflink.com", "Europe", "Berlin / remote", ()),
    ("Getir", "getir.com", "Europe", "London / remote", ()),
    ("Rohlik", "rohlik.cz", "Europe", "Prague / remote", ()),
    ("Amie", "amie.so", "Europe", "Berlin / remote", ()),
    ("Morgen", "morgen.so", "Europe", "Berlin / remote", ()),
    ("MailerLite", "mailerlite.com", "Europe", "Vilnius / remote", ()),
    ("Omnisend", "omnisend.com", "Europe", "Vilnius / remote", ()),
    ("Brevo", "brevo.com", "Europe", "Paris / remote", ()),
    ("ConfigCat", "configcat.com", "Europe", "Budapest / remote", ()),
    ("Unleash", "getunleash.io", "Europe", "Oslo / remote", ()),
    ("ChartMogul", "chartmogul.com", "Europe", "Berlin / remote", ()),
    ("Simple Analytics", "simpleanalytics.com", "Europe", "Amsterdam / remote", ()),
    ("Better Stack", "betterstack.com", "Europe", "Prague / remote", ()),
    ("Checkly", "checklyhq.com", "Europe", "Amsterdam / remote", ()),
    ("Smartlook", "smartlook.com", "Europe", "Brno / remote", ()),
    ("AB Tasty", "abtasty.com", "Europe", "Paris / remote", ()),
    ("Nosto", "nosto.com", "Europe", "Helsinki / remote", ()),
    ("Make", "make.com", "Europe", "Prague / remote", ()),
    ("Windmill", "windmill.dev", "Europe", "Paris / remote", ()),
    ("Kestra", "kestra.io", "Europe", "Paris / remote", ()),
    ("Restate", "restate.dev", "Europe", "Berlin / remote", ()),
    ("Heetch", "heetch.com", "Europe", "Paris / remote", ()),
    ("Omio", "omio.com", "Europe", "Berlin / remote", ()),
    ("Freetrade", "freetrade.io", "Europe", "London / remote", ()),
    ("Scalable Capital", "scalable.capital", "Europe", "Munich / remote", ()),
    ("Personio EU", "personio.com", "Europe", "Munich / remote", ()),
    ("Spendesk EU", "spendesk.com", "Europe", "Paris / remote", ()),
    ("Payhawk EU", "payhawk.com", "Europe", "London / remote", ()),
    ("Trade Republic EU", "traderepublic.com", "Europe", "Berlin / remote", ()),
    ("Wolt EU", "wolt.com", "Europe", "Helsinki / remote", ()),
    ("Too Good To Go EU", "toogoodtogo.com", "Europe", "Copenhagen / remote", ()),
    ("Contentsquare EU", "contentsquare.com", "Europe", "Paris / remote", ()),
    ("Jumia", "jumia.com", "Egypt", "Cairo / remote", ()),
    ("Atome", "atome.sg", "Singapore", "Singapore / remote", ()),
    ("Garena", "garena.com", "Singapore", "Singapore / remote", ()),
    ("Sanity", "sanity.io", "Remote", "Worldwide remote", ()),
    ("Payload", "payloadcms.com", "Remote", "Worldwide remote", ()),
    ("Kit", "kit.com", "Remote", "Worldwide remote", ()),
    ("Buttondown", "buttondown.com", "Remote", "Worldwide remote", ()),
    ("Statsig", "statsig.com", "Remote", "Worldwide remote", ()),
    ("GrowthBook", "growthbook.io", "Remote", "Worldwide remote", ()),
    ("Flagsmith", "flagsmith.com", "Remote", "Worldwide remote", ()),
    ("Svix", "svix.com", "Remote", "Worldwide remote", ()),
    ("Hookdeck", "hookdeck.com", "Remote", "Worldwide remote", ()),
    ("Knock", "knock.app", "Remote", "Worldwide remote", ()),
    ("Courier", "courier.com", "Remote", "Worldwide remote", ()),
    ("Polar", "polar.sh", "Remote", "Worldwide remote", ()),
    ("Lemon Squeezy", "lemonsqueezy.com", "Remote", "Worldwide remote", ()),
    ("Gumroad", "gumroad.com", "Remote", "Worldwide remote", ()),
    ("Baremetrics", "baremetrics.com", "Remote", "Worldwide remote", ()),
    ("Fathom Analytics", "usefathom.com", "Remote", "Worldwide remote", ()),
    ("LogRocket", "logrocket.com", "Remote", "Worldwide remote", ()),
    ("Pinecone", "pinecone.io", "Remote", "Worldwide remote", ()),
    ("Upstash", "upstash.com", "Remote", "Worldwide remote", ()),
    ("ClickHouse", "clickhouse.com", "Remote", "Worldwide remote", ()),
    ("Prefect", "prefect.io", "Remote", "Worldwide remote", ()),
    ("Dagster", "dagster.io", "Remote", "Worldwide remote", ()),
    ("Pipedream", "pipedream.com", "Remote", "Worldwide remote", ()),
    ("Fillout", "fillout.com", "Remote", "Worldwide remote", ()),
    ("Jotform", "jotform.com", "Remote", "Worldwide remote", ()),
    ("Typesense", "typesense.org", "Remote", "Worldwide remote", ()),
    ("Xata", "xata.io", "Remote", "Worldwide remote", ()),
    ("Turso", "turso.tech", "Remote", "Worldwide remote", ()),
    ("MotherDuck", "motherduck.com", "Remote", "Worldwide remote", ()),
    ("Hatchet", "hatchet.run", "Remote", "Worldwide remote", ()),
    ("Calendly", "calendly.com", "Remote", "Worldwide remote", ()),
    ("SavvyCal", "savvycal.com", "Remote", "Worldwide remote", ()),
    ("Motion", "usemotion.com", "Remote", "Worldwide remote", ()),
    ("Reclaim", "reclaim.ai", "Remote", "Worldwide remote", ()),
    ("Clockwise", "clockwise.so", "Remote", "Worldwide remote", ()),
    ("Kraken", "kraken.com", "Remote", "Worldwide remote", ()),
    # Extra MENA / GCC product startups
    ("Tabby KSA", "tabby.ai", "KSA", "Riyadh / remote", ()),
    ("Tamara KSA", "tamara.co", "KSA", "Riyadh / remote", ()),
    ("Postpay UAE", "postpay.io", "UAE", "Dubai / remote", ()),
    ("Paymob Egypt", "paymob.com", "Egypt", "Cairo / remote", ()),
    ("Telr UAE", "telr.com", "UAE", "Dubai / remote", ()),
    ("Namshi UAE", "namshi.com", "UAE", "Dubai / remote", ()),
    ("Mumzworld UAE", "mumzworld.com", "UAE", "Dubai / remote", ()),
    ("Breadfast Egypt", "breadfast.com", "Egypt", "Cairo / remote", ()),
    ("Elmenus Egypt", "elmenus.com", "Egypt", "Cairo / remote", ()),
    ("Cafu UAE", "cafu.com", "UAE", "Dubai / remote", ()),
    ("Lean KSA", "leantech.me", "KSA", "Riyadh / remote", ()),
    ("Tarabut Bahrain", "tarabut.com", "Bahrain", "Manama / remote", ()),
    ("Snoonu Remote", "snoonu.com", "Qatar", "Doha / remote", ()),
    ("Tap KSA", "tap.company", "KSA", "Riyadh / remote", ()),
    ("Moyasar KSA", "moyasar.com", "KSA", "Riyadh / remote", ()),
    ("PayTabs KSA", "paytabs.com", "KSA", "Riyadh / remote", ()),
    # Extra Europe product / AI
    ("Lovable EU", "lovable.dev", "Europe", "Europe / remote", ()),
    ("Langfuse EU", "langfuse.com", "Europe", "Berlin / remote", ()),
    ("PostHog EU", "posthog.com", "Europe", "Europe / remote", ()),
    ("Cal.com EU", "cal.com", "Europe", "Europe / remote", ()),
    ("Plausible EU", "plausible.io", "Europe", "Europe / remote", ()),
    ("Strapi EU", "strapi.io", "Europe", "Paris / remote", ()),
    ("Framer EU", "framer.com", "Europe", "Amsterdam / remote", ()),
    ("Mistral EU", "mistral.ai", "Europe", "Paris / remote", ()),
    ("Photoroom EU", "photoroom.com", "Europe", "Paris / remote", ()),
    ("ElevenLabs EU", "elevenlabs.io", "Europe", "London / remote", ()),
    ("Synthesia EU", "synthesia.io", "Europe", "London / remote", ()),
    ("Stability AI EU", "stability.ai", "Europe", "London / remote", ()),
    ("DeepL EU", "deepl.com", "Europe", "Cologne / remote", ()),
    ("Aleph Alpha EU", "aleph-alpha.com", "Europe", "Heidelberg / remote", ()),
    ("Qdrant EU", "qdrant.tech", "Europe", "Berlin / remote", ()),
    ("Weaviate EU", "weaviate.io", "Europe", "Amsterdam / remote", ()),
    ("deepset EU", "deepset.ai", "Europe", "Berlin / remote", ()),
    ("Meilisearch EU", "meilisearch.com", "Europe", "Paris / remote", ()),
    ("Algolia EU", "algolia.com", "Europe", "Paris / remote", ()),
    ("Contentful EU", "contentful.com", "Europe", "Berlin / remote", ()),
    ("Intercom EU", "intercom.com", "Europe", "Dublin / remote", ()),
    ("Typeform EU", "typeform.com", "Europe", "Barcelona / remote", ()),
    ("Factorial EU", "factorialhr.com", "Europe", "Barcelona / remote", ()),
    ("TravelPerk EU", "travelperk.com", "Europe", "Barcelona / remote", ()),
    ("Remote.com EU", "remote.com", "Europe", "Lisbon / remote", ()),
    ("Doist EU", "doist.com", "Europe", "Europe / remote", ()),
    ("Toggl EU", "toggl.com", "Europe", "Tallinn / remote", ()),
    ("Hotjar EU", "hotjar.com", "Europe", "Malta / remote", ()),
    ("GitBook EU", "gitbook.com", "Europe", "Europe / remote", ()),
    ("Bunny.net EU", "bunny.net", "Europe", "Slovenia / remote", ()),
    ("Hetzner EU", "hetzner.com", "Europe", "Germany / remote", ()),
    ("Nextcloud EU", "nextcloud.com", "Europe", "Stuttgart / remote", ()),
    ("Proton EU", "proton.me", "Europe", "Geneva / remote", ()),
    ("Element EU", "element.io", "Europe", "London / remote", ()),
    ("Nord Security EU", "nordsecurity.com", "Europe", "Vilnius / remote", ()),
    ("Mullvad EU", "mullvad.net", "Europe", "Gothenburg / remote", ()),
    ("Vivaldi EU", "vivaldi.com", "Europe", "Oslo / remote", ()),
    ("Ecosia EU", "ecosia.org", "Europe", "Berlin / remote", ()),
    ("Qwant EU", "qwant.com", "Europe", "Paris / remote", ()),
    ("Tuta EU", "tuta.com", "Europe", "Hannover / remote", ()),
    ("Tresorit EU", "tresorit.com", "Europe", "Zurich / remote", ()),
    ("pCloud EU", "pcloud.com", "Europe", "Sofia / remote", ()),
    ("Bitdefender EU", "bitdefender.com", "Europe", "Bucharest / remote", ()),
    ("Preply EU", "preply.com", "Europe", "Kyiv / remote", ()),
    ("Ajax Systems EU", "ajax.systems", "Europe", "Kyiv / remote", ()),
    ("Bolt EU", "bolt.eu", "Europe", "Tallinn / remote", ()),
    ("Pipedrive EU", "pipedrive.com", "Europe", "Tallinn / remote", ()),
    ("Veriff EU", "veriff.com", "Europe", "Tallinn / remote", ()),
    ("Aiven EU", "aiven.io", "Europe", "Helsinki / remote", ()),
    ("Smartly EU", "smartly.io", "Europe", "Helsinki / remote", ()),
    ("RELEX EU", "relexsolutions.com", "Europe", "Helsinki / remote", ()),
    ("Supermetrics EU", "supermetrics.com", "Europe", "Helsinki / remote", ()),
    ("ICEYE EU", "iceye.com", "Europe", "Helsinki / remote", ()),
    ("Klarna EU", "klarna.com", "Europe", "Stockholm / remote", ()),
    ("Spotify EU", "spotify.com", "Europe", "Stockholm / remote", ()),
    ("Truecaller EU", "truecaller.com", "Europe", "Stockholm / remote", ()),
    ("Voi EU", "voi.com", "Europe", "Stockholm / remote", ()),
    ("Trustly EU", "trustly.com", "Europe", "Stockholm / remote", ()),
    ("King EU", "king.com", "Europe", "Stockholm / remote", ()),
    ("Epidemic Sound EU", "epidemicsound.com", "Europe", "Stockholm / remote", ()),
    ("Zettle EU", "zettle.com", "Europe", "Stockholm / remote", ()),
    ("Trustpilot EU", "trustpilot.com", "Europe", "Copenhagen / remote", ()),
    ("Lunar EU", "lunar.app", "Europe", "Copenhagen / remote", ()),
    ("Pleo EU", "pleo.io", "Europe", "Copenhagen / remote", ()),
    ("Kahoot EU", "kahoot.com", "Europe", "Oslo / remote", ()),
    ("Cognite EU", "cognite.com", "Europe", "Oslo / remote", ()),
    ("Visma EU", "visma.com", "Europe", "Oslo / remote", ()),
    ("Xeneta EU", "xeneta.com", "Europe", "Oslo / remote", ()),
    ("Oda EU", "oda.com", "Europe", "Oslo / remote", ()),
)


def _clean_emails(emails: list[str], domain: str) -> list[str]:
    out: list[str] = []
    for email in emails:
        email = email.lower().strip()
        local, _, host = email.partition("@")
        if not local or not host:
            continue
        if any(j in local for j in JUNK_LOCAL):
            continue
        if host in {"gmail.com", "yahoo.com", "hotmail.com", "outlook.com"}:
            continue
        if domain and not (host == domain or host.endswith("." + domain) or domain.endswith(host)):
            if not any(tok in local for tok in ("hr", "career", "recruit", "talent", "people", "job", "hiring")):
                continue
        out.append(email)
    return list(dict.fromkeys(out))


def scrape_directory_contacts(
    max_workers: int = 16,
    *,
    regions: set[str] | None = None,
) -> list[CompanyContact]:
    contacts: list[CompanyContact] = []
    rows = COMPANY_DIRECTORY
    if regions:
        rows = tuple(r for r in COMPANY_DIRECTORY if r[2] in regions)

    def one(row: tuple[str, str, str, str, tuple[str, ...]]) -> CompanyContact | None:
        name, domain, region, city, known = row
        if domain.lower() in BLOCKED_DIRECTORY_DOMAINS or name.strip().lower() in BLOCKED_DIRECTORY_NAMES:
            return None
        local = HttpClient()
        try:
            scraped = _scrape_contact_emails(local, domain)
        finally:
            local.close()
        emails = _clean_emails([*known, *scraped], domain)
        source = ""
        if known and scraped:
            source = "known + company website"
        elif known:
            source = "known company contact"
        elif scraped:
            source = "company website"
        else:
            emails = guess_generic_emails(domain)[:2]
            source = "guessed pattern (verify before sending)"
        return CompanyContact(
            name=name,
            domain=domain,
            region=region,
            city=city,
            emails=emails,
            email_source=source,
            careers_url=f"https://{domain}/careers",
        )

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futs = [pool.submit(one, row) for row in rows]
        for fut in as_completed(futs):
            contact = fut.result()
            if contact is not None:
                contacts.append(contact)
    contacts.sort(key=lambda c: (REGION_ORDER.get(c.region, 11), c.name.lower()))
    return contacts


def contacts_from_jobs(jobs) -> list[CompanyContact]:
    """Unique companies from live job matches (skip junk / ATS guesses)."""
    by_company: dict[str, CompanyContact] = {}
    for job in jobs:
        name = (job.company or "").strip()
        if not name:
            continue
        if name.lower() in BLOCKED_DIRECTORY_NAMES or "codet.ai" in name.lower():
            continue
        key = name.lower()
        email = (job.hr_email or "").lower()
        if not email:
            continue
        if email.endswith("@codet.ai") or email.endswith("@codet.com") or ".codet.ai" in email:
            continue
        if (job.company_domain or "").lower() in BLOCKED_DIRECTORY_DOMAINS:
            continue
        local = email.split("@")[0]
        if any(j in local for j in JUNK_LOCAL):
            continue
        if "guess" in (job.email_source or "").lower() and not job.company_domain:
            continue
        region = "Remote"
        loc = f"{job.location} {job.location_fit} {job.pakistan_friendly}".lower()
        if "karachi" in loc:
            region = "Karachi"
        elif "pakistan" in loc or job.pakistan_friendly == "Yes":
            region = "Pakistan"
        elif any(
            t in loc
            for t in (
                "london",
                "berlin",
                "amsterdam",
                "paris",
                "dublin",
                "lisbon",
                "barcelona",
                "madrid",
                "stockholm",
                "copenhagen",
                "helsinki",
                "tallinn",
                "oslo",
                "zurich",
                "munich",
                "europe",
                "emea",
                "united kingdom",
                "uk remote",
                "germany",
                "netherlands",
                "france",
                "portugal",
                "spain",
                "ireland",
                "nordic",
            )
        ):
            region = "Europe"
        elif any(
            t in loc
            for t in (
                "australia",
                "sydney",
                "melbourne",
                "brisbane",
                "perth",
                "adelaide",
                "canberra",
                "auckland",
                "new zealand",
            )
        ):
            region = "Australia"
        elif any(
            t in loc
            for t in (
                "uae",
                "dubai",
                "riyadh",
                "saudi",
                "egypt",
                "cairo",
                "qatar",
                "doha",
                "bahrain",
                "kuwait",
                "jordan",
                "lebanon",
                "israel",
                "tel aviv",
                "mena",
                "middle east",
            )
        ):
            region = "MENA"
        existing = by_company.get(key)
        emails = _clean_emails([email, *job.emails], job.company_domain)
        if not emails:
            continue
        if existing is None:
            by_company[key] = CompanyContact(
                name=name,
                domain=job.company_domain,
                region=region,
                city=job.location or region,
                emails=emails,
                email_source=job.email_source,
                careers_url=job.url,
                sample_role=job.title,
                apply_url=job.url,
            )
            continue
        existing.emails = list(dict.fromkeys([*existing.emails, *emails]))
        if job.title and not existing.sample_role:
            existing.sample_role = job.title
            existing.apply_url = job.url
        if region == "Karachi":
            existing.region = "Karachi"
        elif region == "Europe" and existing.region not in {"Karachi", "Pakistan", "MENA", "UAE", "KSA", "Qatar"}:
            existing.region = "Europe"
        elif region == "MENA" and existing.region not in {"Karachi", "Pakistan"}:
            existing.region = "MENA"
    return list(by_company.values())


def contacts_from_csv(path: Path) -> list[CompanyContact]:
    if not path.exists():
        return []
    out: list[CompanyContact] = []
    with path.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            email = (row.get("HR / Recruiter Email") or "").strip().lower()
            if not email:
                continue
            others = [e.strip() for e in (row.get("Other Emails") or "").split(",") if e.strip()]
            out.append(
                CompanyContact(
                    name=(row.get("Company") or "").strip(),
                    domain=(row.get("Domain") or "").strip(),
                    region=(row.get("Region") or "Remote").strip() or "Remote",
                    city=(row.get("City") or "").strip(),
                    emails=[email, *others],
                    email_source=(row.get("Email Source") or "").strip(),
                    careers_url=(row.get("Careers / Apply URL") or "").strip(),
                    sample_role=(row.get("Sample Role") or "").strip(),
                    apply_url=(row.get("Careers / Apply URL") or "").strip(),
                )
            )
    return out


def merge_contacts(directory: list[CompanyContact], from_jobs: list[CompanyContact]) -> list[CompanyContact]:
    by_key: dict[str, CompanyContact] = {}
    for c in [*directory, *from_jobs]:
        key = (c.domain or c.name).strip().lower()
        existing = by_key.get(key)
        if existing is None:
            by_key[key] = c
            continue
        existing.emails = list(dict.fromkeys([*existing.emails, *c.emails]))
        if c.sample_role and not existing.sample_role:
            existing.sample_role = c.sample_role
            existing.apply_url = c.apply_url
        if c.email_source.startswith("known") or c.email_source == "company website":
            if "guess" in existing.email_source:
                existing.email_source = c.email_source
        if c.region == "Karachi":
            existing.region = "Karachi"
            existing.city = c.city or existing.city
        elif c.region == "Europe" and existing.region == "Remote":
            existing.region = "Europe"
            existing.city = c.city or existing.city
    out = list(by_key.values())
    out.sort(key=lambda c: (REGION_ORDER.get(c.region, 11), c.name.lower()))
    return out
